import type { User, Post, Book } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alia Rahman',
    avatarUrl: 'https://picsum.photos/seed/av1/100/100',
    level: 2.1,
    institution: 'University of Dhaka',
    location: 'Dhaka, Bangladesh',
    hobbies: ['Classic Literature', 'Poetry', 'History'],
    isFollowing: true,
    isMutual: true,
    isAdmin: true,
  },
  {
    id: 'user-2',
    name: 'Ben Carter',
    avatarUrl: 'https://picsum.photos/seed/av2/100/100',
    level: 1.5,
    institution: 'BRAC University',
    location: 'Chittagong, Bangladesh',
    hobbies: ['Science Fiction', 'Fantasy', 'Gaming'],
    isFollowing: true,
    isMutual: false,
  },
  {
    id: 'user-3',
    name: 'Cathy Liu',
    avatarUrl: 'https://picsum.photos/seed/av3/100/100',
    level: 3.0,
    institution: 'Independent Scholar',
    location: 'Sylhet, Bangladesh',
    hobbies: ['Philosophy', 'Art', 'Travel'],
    isFollowing: false,
    isMutual: false,
  },
    {
    id: 'user-4',
    name: 'David Hasan',
    avatarUrl: 'https://picsum.photos/seed/av4/100/100',
    level: 0.5,
    institution: 'Notre Dame College',
    location: 'Dhaka, Bangladesh',
    hobbies: ['Comics', 'Manga', 'Movies'],
    isFollowing: true,
    isMutual: true,
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    author: mockUsers[0],
    content: "Just finished 'One Hundred Years of Solitude' again. Every read reveals a new layer of magic. What a masterpiece! What are your thoughts on magical realism?",
    imageUrl: 'https://picsum.photos/seed/pi1/800/400',
    likes: 125,
    comments: 42,
    shares: 18,
    createdAt: '2h ago',
  },
  {
    id: 'post-2',
    author: mockUsers[1],
    content: "Excited to start the 'Dune' series! I've heard so much about it. Any tips for a first-time reader? No spoilers, please!",
    likes: 78,
    comments: 15,
    shares: 5,
    createdAt: 'Yesterday',
  },
  {
    id: 'post-3',
    author: mockUsers[2],
    content: 'Exploring the connection between Stoic philosophy and modern mindfulness. It is fascinating how ancient wisdom remains so relevant today.',
    imageUrl: 'https://picsum.photos/seed/pi2/800/400',
    likes: 210,
    comments: 65,
    shares: 33,
    createdAt: '3 days ago',
  },
];

export const mockBooks: Book[] = [
    {
        id: 'book-1',
        title: "Gitanjali",
        author: "Rabindranath Tagore",
        price: 150,
        coverUrl: "https://picsum.photos/seed/bc1/400/600",
        level: '0.0',
    },
    {
        id: 'book-2',
        title: "The Namesake",
        author: "Jhumpa Lahiri",
        price: 350,
        coverUrl: "https://picsum.photos/seed/bc2/400/600",
        level: '0.0',
        category: 'popular',
    },
    {
        id: 'book-3',
        title: "A Golden Age",
        author: "Tahmima Anam",
        price: 400,
        coverUrl: "https://picsum.photos/seed/bc3/400/600",
        level: '0.1',
    },
    {
        id: 'book-4',
        title: "Nineteen Eighty-Four",
        author: "George Orwell",
        price: 250,
        coverUrl: "https://picsum.photos/seed/bc4/400/600",
        level: '1.5',
        category: 'popular',
    },
     {
        id: 'book-5',
        title: "Feluda Samagra 1",
        author: "Satyajit Ray",
        price: 500,
        coverUrl: "https://picsum.photos/seed/bc5/400/600",
        level: '0.2',
    },
    {
        id: 'book-6',
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 300,
        coverUrl: "https://picsum.photos/seed/bc6/400/600",
        level: '0.2',
        category: 'popular',
    },
    {
        id: 'book-7',
        title: "English Grammar in Use",
        author: "Raymond Murphy",
        price: 450,
        coverUrl: "https://picsum.photos/seed/bc7/400/600",
        level: 'all',
        category: 'vocab_grammar',
    },
    {
        id: 'book-8',
        title: "Word Power Made Easy",
        author: "Norman Lewis",
        price: 220,
        coverUrl: "https://picsum.photos/seed/bc8/400/600",
        level: 'all',
        category: 'vocab_grammar',
    },
];
