import type { User, Post, Book, ExamResult, Transaction, PrizeWinner } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alia Rahman',
    avatarUrl: 'https://picsum.photos/seed/av1/100/100',
    level: 2.1,
    institution: 'University of Dhaka',
    location: 'Dhaka, Bangladesh',
    hobbies: ['Classic Literature', 'Poetry', 'History'],
    isFollowing: true,
    isMutual: true,
    isAdmin: true,
  },
  {
    id: 'user-2',
    name: 'Ben Carter',
    avatarUrl: 'https://picsum.photos/seed/av2/100/100',
    level: 1.5,
    institution: 'BRAC University',
    location: 'Chittagong, Bangladesh',
    hobbies: ['Science Fiction', 'Fantasy', 'Gaming'],
    isFollowing: true,
    isMutual: false,
  },
  {
    id: 'user-3',
    name: 'Cathy Liu',
    avatarUrl: 'https://picsum.photos/seed/av3/100/100',
    level: 3.0,
    institution: 'Independent Scholar',
    location: 'Sylhet, Bangladesh',
    hobbies: ['Philosophy', 'Art', 'Travel'],
    isFollowing: false,
    isMutual: false,
  },
    {
    id: 'user-4',
    name: 'David Hasan',
    avatarUrl: 'https://picsum.photos/seed/av4/100/100',
    level: 0.5,
    institution: 'Notre Dame College',
    location: 'Dhaka, Bangladesh',
    hobbies: ['Comics', 'Manga', 'Movies'],
    isFollowing: true,
    isMutual: true,
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    author: mockUsers[0],
    content: "Just finished 'One Hundred Years of Solitude' again. Every read reveals a new layer of magic. What a masterpiece! What are your thoughts on magical realism?",
    imageUrl: 'https://picsum.photos/seed/pi1/800/400',
    likes: 125,
    comments: 42,
    shares: 18,
    createdAt: '2h ago',
  },
  {
    id: 'post-2',
    author: mockUsers[1],
    content: "Excited to start the 'Dune' series! I've heard so much about it. Any tips for a first-time reader? No spoilers, please!",
    likes: 78,
    comments: 15,
    shares: 5,
    createdAt: 'Yesterday',
  },
  {
    id: 'post-3',
    author: mockUsers[2],
    content: 'Exploring the connection between Stoic philosophy and modern mindfulness. It is fascinating how ancient wisdom remains so relevant today.',
    imageUrl: 'https://picsum.photos/seed/pi2/800/400',
    likes: 210,
    comments: 65,
    shares: 33,
    createdAt: '3 days ago',
  },
];

export const mockBooks: Book[] = [
    {
        id: 'book-1',
        title: "Gitanjali",
        author: "Rabindranath Tagore",
        price: 150,
        coverUrl: "https://picsum.photos/seed/bc1/400/600",
        level: '0.0',
    },
    {
        id: 'book-2',
        title: "The Namesake",
        author: "Jhumpa Lahiri",
        price: 350,
        coverUrl: "https://picsum.photos/seed/bc2/400/600",
        level: '0.0',
        category: 'popular',
    },
    {
        id: 'book-3',
        title: "A Golden Age",
        author: "Tahmima Anam",
        price: 400,
        coverUrl: "https://picsum.photos/seed/bc3/400/600",
        level: '0.1',
    },
    {
        id: 'book-4',
        title: "Nineteen Eighty-Four",
        author: "George Orwell",
        price: 250,
        coverUrl: "https://picsum.photos/seed/bc4/400/600",
        level: '1.5',
        category: 'popular',
    },
     {
        id: 'book-5',
        title: "Feluda Samagra 1",
        author: "Satyajit Ray",
        price: 500,
        coverUrl: "https://picsum.photos/seed/bc5/400/600",
        level: '0.2',
    },
    {
        id: 'book-6',
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 300,
        coverUrl: "https://picsum.photos/seed/bc6/400/600",
        level: '0.2',
        category: 'popular',
    },
    {
        id: 'book-7',
        title: "English Grammar in Use",
        author: "Raymond Murphy",
        price: 450,
        coverUrl: "https://picsum.photos/seed/bc7/400/600",
        level: 'all',
        category: 'vocab_grammar',
    },
    {
        id: 'book-8',
        title: "Word Power Made Easy",
        author: "Norman Lewis",
        price: 220,
        coverUrl: "https://picsum.photos/seed/bc8/400/600",
        level: 'all',
        category: 'vocab_grammar',
    },
];

export const mockExamResults: ExamResult[] = [
  {
    id: 'result-1',
    userId: 'user-2',
    userName: 'Ben Carter',
    userAvatarUrl: 'https://picsum.photos/seed/av2/100/100',
    level: '1.5',
    totalMarks: 20,
    totalObtainedMarks: 15,
    totalPercentage: 75,
    overallStatus: 'Passed',
    subjects: [
      { subject: 'Bengali', totalMarks: 10, obtainedMarks: 8, percentage: 80, status: 'Passed' },
      { subject: 'English', totalMarks: 10, obtainedMarks: 7, percentage: 70, status: 'Passed' },
    ],
    examDate: '2024-07-22',
  },
  {
    id: 'result-2',
    userId: 'user-4',
    userName: 'David Hasan',
    userAvatarUrl: 'https://picsum.photos/seed/av4/100/100',
    level: '0.5',
    totalMarks: 30,
    totalObtainedMarks: 17,
    totalPercentage: 56.67,
    overallStatus: 'Failed',
    subjects: [
        { subject: 'Bengali', totalMarks: 15, obtainedMarks: 10, percentage: 66.67, status: 'Passed' },
        { subject: 'English', totalMarks: 15, obtainedMarks: 7, percentage: 46.67, status: 'Failed' },
    ],
    examDate: '2024-07-21',
  },
    {
    id: 'result-3',
    userId: 'user-3',
    userName: 'Cathy Liu',
    userAvatarUrl: 'https://picsum.photos/seed/av3/100/100',
    level: '3.0',
    totalMarks: 25,
    totalObtainedMarks: 22,
    totalPercentage: 88,
    overallStatus: 'Passed',
    subjects: [
        { subject: 'Bengali', totalMarks: 15, obtainedMarks: 13, percentage: 86.67, status: 'Passed' },
        { subject: 'English', totalMarks: 10, obtainedMarks: 9, percentage: 90, status: 'Passed' },
    ],
    examDate: '2024-07-19',
  },
  {
    id: 'result-4',
    userId: 'user-1',
    userName: 'Alia Rahman',
    userAvatarUrl: 'https://picsum.photos/seed/av1/100/100',
    level: '2.0',
    totalMarks: 20,
    totalObtainedMarks: 18,
    totalPercentage: 90,
    overallStatus: 'Passed',
    subjects: [
      { subject: 'Bengali', totalMarks: 10, obtainedMarks: 9, percentage: 90, status: 'Passed' },
      { subject: 'English', totalMarks: 10, obtainedMarks: 9, percentage: 90, status: 'Passed' },
    ],
    examDate: '2024-07-25',
  },
  {
    id: 'result-5',
    userId: 'user-1',
    userName: 'Alia Rahman',
    userAvatarUrl: 'https://picsum.photos/seed/av1/100/100',
    level: '1.9',
    totalMarks: 20,
    totalObtainedMarks: 11,
    totalPercentage: 55,
    overallStatus: 'Failed',
    subjects: [
      { subject: 'Bengali', totalMarks: 10, obtainedMarks: 6, percentage: 60, status: 'Passed' },
      { subject: 'English', totalMarks: 10, obtainedMarks: 5, percentage: 50, status: 'Failed' },
    ],
    examDate: '2024-07-20',
  },
  {
    id: 'result-6',
    userId: 'user-4',
    userName: 'David Hasan',
    userAvatarUrl: 'https://picsum.photos/seed/av4/100/100',
    level: '0.0',
    totalMarks: 60,
    totalObtainedMarks: 45,
    totalPercentage: 75,
    overallStatus: 'Passed',
    subjects: [
      { subject: 'Bengali', totalMarks: 30, obtainedMarks: 20, percentage: 66.67, status: 'Passed' },
      { subject: 'English', totalMarks: 30, obtainedMarks: 25, percentage: 83.33, status: 'Passed' },
    ],
    examDate: '2024-07-28',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'txn-1',
    date: '2024-07-22',
    type: 'Exam Fee',
    amount: 20,
    userId: 'user-2',
    userName: 'Ben Carter',
    status: 'Completed'
  },
  {
    id: 'txn-2',
    date: '2024-07-22',
    type: 'Book Shop',
    amount: 800,
    userId: 'user-3',
    userName: 'Cathy Liu',
    status: 'Completed'
  },
  {
    id: 'txn-3',
    date: '2024-07-21',
    type: 'Patronage',
    amount: 1000,
    userId: 'user-1',
    userName: 'Alia Rahman',
    status: 'Completed'
  },
  {
    id: 'txn-4',
    date: '2024-07-19',
    type: 'Exam Fee',
    amount: 20,
    userId: 'user-4',
    userName: 'David Hasan',
    status: 'Completed'
  },
];

export const mockPrizeWinners: PrizeWinner[] = [
  {
    id: 'prize-1',
    userId: 'user-3',
    userName: 'Cathy Liu',
    userAvatarUrl: 'https://picsum.photos/seed/av3/100/100',
    level: '3.0',
    prize: 'BDT 500 Book Coupon',
    status: 'Pending',
  },
  {
    id: 'prize-2',
    userId: 'user-1',
    userName: 'Alia Rahman',
    userAvatarUrl: 'https://picsum.photos/seed/av1/100/100',
    level: '2.1',
    prize: 'BDT 250 Book Coupon',
    status: 'Awarded',
    dateAwarded: '2024-07-23'
  },
];
