
import type { Question } from './types';

export const newBengaliLevel8Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: "'ব্যক্তিত্বের বিকাশ' বইটির রচয়িতা কে?",
    answers: [
      { text: 'শ্রী রামকৃষ্ণ', isCorrect: false },
      { text: 'স্বামী বিবেকানন্দ', isCorrect: true },
      { text: 'সারদা দেবী', isCorrect: false },
      { text: 'স্বামী ব্রহ্মানন্দ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্বের পূর্ণ বিকাশের জন্য মানবমনের কয়টি পর্যায়ের কথা বলা হয়েছে?',
    answers: [
      { text: 'দুইটি', isCorrect: false },
      { text: 'তিনটি', isCorrect: false },
      { text: 'চারটি', isCorrect: true },
      { text: 'পাঁচটি', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'স্বামীজীর মতে শিক্ষার মূল উদ্দেশ্য কী?',
    answers: [
      { text: 'চাকরি পাওয়া', isCorrect: false },
      { text: 'তথ্য সংগ্রহ', isCorrect: false },
      { text: 'মানুষের অন্তর্নিহিত দেবত্বের বিকাশ', isCorrect: true },
      { text: 'মুখস্থ বিদ্যা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্ব বলতে স্বামীজী প্রধানত কী বুঝিয়েছেন?',
    answers: [
      { text: 'সুন্দর চেহারা', isCorrect: false },
      { text: 'পোশাক-আশাক', isCorrect: false },
      { text: 'মানসিক ও আধ্যাত্মিক শক্তি', isCorrect: true },
      { text: 'বাচনভঙ্গি', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মানুষের সকল শক্তির উৎস কী?',
    answers: [
      { text: 'শরীর', isCorrect: false },
      { text: 'টাকা', isCorrect: false },
      { text: 'আত্মা বা আত্মশক্তি', isCorrect: true },
      { text: 'সমাজ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'স্বামীজীর মতে কোনটি মানুষের বড় শত্রু?',
    answers: [
      { text: 'দারিদ্র্য', isCorrect: false },
      { text: 'ভয় ও দুর্বলতা', isCorrect: true },
      { text: 'শত্রু', isCorrect: false },
      { text: 'অশিক্ষা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: "'চরিত্র' বলতে কী বোঝায়?",
    answers: [
      { text: 'স্বভাবের সমষ্টি', isCorrect: true },
      { text: 'বংশ পরিচয়', isCorrect: false },
      { text: 'আর্থিক অবস্থা', isCorrect: false },
      { text: 'নাম-যশ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'একাগ্রতা বা মনোযোগ বৃদ্ধির উপায় কী?',
    answers: [
      { text: 'বেশি ঘুমানো', isCorrect: false },
      { text: 'মনের সংযম ও ধ্যান', isCorrect: true },
      { text: 'গল্প করা', isCorrect: false },
      { text: 'দ্রুত পড়া', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: '"জীবই শিব"—এই বাণীর প্রবক্তা কে?',
    answers: [
      { text: 'রবীন্দ্রনাথ ঠাকুর', isCorrect: false },
      { text: 'বিদ্যাসাগর', isCorrect: false },
      { text: 'স্বামী বিবেকানন্দ', isCorrect: true },
      { text: 'মহাত্মা গান্ধী', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'আদর্শ ব্যক্তিত্বের লক্ষণ কী?',
    answers: [
      { text: 'অস্থিরতা', isCorrect: false },
      { text: 'আত্মবিশ্বাস ও স্থিরতা', isCorrect: true },
      { text: 'দম্ভ', isCorrect: false },
      { text: 'চপলতা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'কিসের অভাবে প্রতিভা থাকা সত্ত্বেও মানুষ সফল হয় না?',
    answers: [
      { text: 'অর্থের', isCorrect: false },
      { text: 'ব্যক্তিত্বের ও ইচ্ছাশক্তির', isCorrect: true },
      { text: 'ডিগ্রির', isCorrect: false },
      { text: 'রূপের', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'স্বামীজীর মতে কোন শক্তিটি মহত্তম?',
    answers: [
      { text: 'পেশীশক্তি', isCorrect: false },
      { text: 'বুদ্ধিবৃত্তি', isCorrect: false },
      { text: 'প্রেম ও আধ্যাত্মিক শক্তি', isCorrect: true },
      { text: 'রাজনৈতিক শক্তি', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: "'ব্যক্তিত্বের বিকাশ' বইটির প্রকাশক কারা?",
    answers: [
      { text: 'আনন্দ পাবলিশার্স', isCorrect: false },
      { text: 'উদ্বোধন কার্যালয়', isCorrect: true },
      { text: 'দে\'জ পাবলিশিং', isCorrect: false },
      { text: 'সাহিত্য সংসদ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'চরিত্র গঠনের জন্য প্রথম প্রয়োজন কোনটি?',
    answers: [
      { text: 'আলস্য', isCorrect: false },
      { text: 'ব্রহ্মচর্য বা বীর্য রক্ষা', isCorrect: true },
      { text: 'বিলাসিতা', isCorrect: false },
      { text: 'পরনিন্দা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'সফলতার জন্য মনের কোন অবস্থা প্রয়োজন?',
    answers: [
      { text: 'দ্বিধা', isCorrect: false },
      { text: 'একাগ্রতা', isCorrect: true },
      { text: 'বিষাদ', isCorrect: false },
      { text: 'চঞ্চলতা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মানুষের প্রকৃত স্বরূপ কী?',
    answers: [
      { text: 'মরণশীল দেহ', isCorrect: false },
      { text: 'অবিনাশী আত্মা', isCorrect: true },
      { text: 'নাম ও ধাম', isCorrect: false },
      { text: 'কেবল রক্ত-মাংস', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'আত্মবিশ্বাস বলতে কী বোঝায়?',
    answers: [
      { text: 'নিজের ওপর দম্ভ', isCorrect: false },
      { text: 'নিজের ভেতরের অসীম শক্তিতে বিশ্বাস', isCorrect: true },
      { text: 'অন্যকে তুচ্ছ করা', isCorrect: false },
      { text: 'কেবল জেদ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'স্বামীজী কোনটিকে \'পাপ\' বলেছেন?',
    answers: [
      { text: 'মিথ্যা বলা', isCorrect: false },
      { text: 'দুর্বলতাকে', isCorrect: true },
      { text: 'খেলাধুলাকে', isCorrect: false },
      { text: 'গান গাওয়াকে', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্বের প্রভাবে মানুষ কী করে?',
    answers: [
      { text: 'ভয় পায়', isCorrect: false },
      { text: 'অন্যকে আকৃষ্ট ও প্রভাবিত করে', isCorrect: true },
      { text: 'হীনম্মন্যতায় ভোগে', isCorrect: false },
      { text: 'স্বার্থপর হয়', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মনের সংযমকে কী বলা হয়?',
    answers: [
      { text: 'বৈরাগ্য', isCorrect: false },
      { text: 'যোগ', isCorrect: true },
      { text: 'ক্রোধ', isCorrect: false },
      { text: 'মোহ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'কোনটি ব্যক্তিত্বকে ধ্বংস করে?',
    answers: [
      { text: 'সেবা', isCorrect: false },
      { text: 'ঘৃণা ও ঈর্ষা', isCorrect: true },
      { text: 'বিনয়', isCorrect: false },
      { text: 'ক্ষমা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মানুষের আসল পরিচয় কিসে?',
    answers: [
      { text: 'পোশাকে', isCorrect: false },
      { text: ' চরিত্রে', isCorrect: true },
      { text: 'ব্যাংক ব্যালেন্সে', isCorrect: false },
      { text: 'গলার স্বরে', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'শিক্ষার মাধ্যমে কী হওয়া উচিত?',
    answers: [
      { text: 'যন্ত্র', isCorrect: false },
      { text: 'মানুষ', isCorrect: true },
      { text: 'গোলাম', isCorrect: false },
      { text: 'পণ্ডিত', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'কার আদর্শে ব্যক্তিত্বের পূর্ণ বিকাশ সম্ভব?',
    answers: [
      { text: 'লোভী ব্যক্তির', isCorrect: false },
      { text: 'ত্যাগী ও সংযমী ব্যক্তির', isCorrect: true },
      { text: 'অহংকারী ব্যক্তির', isCorrect: false },
      { text: 'কুঁড়ে ব্যক্তির', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'জগতের সব মহৎ কাজ কিসের দ্বারা সম্পন্ন হয়?',
    answers: [
      { text: 'তর্কের দ্বারা', isCorrect: false },
      { text: 'মহৎ ব্যক্তিত্বের দ্বারা', isCorrect: true },
      { text: 'অর্থের দ্বারা', isCorrect: false },
      { text: 'অস্ত্রের দ্বারা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্বের বিকাশে শরীরের ভূমিকা কী?',
    answers: [
      { text: 'কোনো ভূমিকা নেই', isCorrect: false },
      { text: 'সুস্থ শরীর সুস্থ মনের আধার', isCorrect: true },
      { text: 'কেবল পেশী গঠন', isCorrect: false },
      { text: 'সুন্দর ত্বক', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ইচ্ছাশক্তিকে সঠিক পথে পরিচালনা করাকে কী বলে?',
    answers: [
      { text: 'রাজনীতি', isCorrect: false },
      { text: 'নীতিশিক্ষা', isCorrect: false },
      { text: 'ব্যক্তিত্বের প্রয়োগ', isCorrect: true },
      { text: 'চালাকি', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'স্বামীজী কিসের ওপর বেশি জোর দিয়েছেন?',
    answers: [
      { text: 'তত্ত্বের ওপর', isCorrect: false },
      { text: 'প্রয়োগ বা অভ্যাসের ওপর', isCorrect: true },
      { text: 'গল্পের ওপর', isCorrect: false },
      { text: 'কল্পনার ওপর', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: '"ওঠো, জাগো..."—এই মন্ত্রটি কাদের জন্য?',
    answers: [
      { text: 'কেবল শিশুদের', isCorrect: false },
      { text: 'সারা বিশ্বের যুবসমাজের', isCorrect: true },
      { text: 'কেবল সন্ন্যাসীদের', isCorrect: false },
      { text: 'বৃদ্ধদের', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'সত্যিকারের নেতা হতে গেলে আগে কী হতে হবে?',
    answers: [
      { text: 'ধনী', isCorrect: false },
      { text: 'সেবক', isCorrect: true },
      { text: 'রাজা', isCorrect: false },
      { text: 'কঠোর', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্বের বিকাশে \'অহঙ্কার\' এর শুদ্ধ রূপ কী?',
    answers: [
      { text: 'দম্ভ', isCorrect: false },
      { text: 'আমি ঈশ্বরের দাস বা সন্তান', isCorrect: true },
      { text: 'নিজেকে বড় ভাবা', isCorrect: false },
      { text: 'অন্যকে গালি দেওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মানুষের ভবিষ্যৎ কার হাতে?',
    answers: [
      { text: 'ভাগ্যের', isCorrect: false },
      { text: 'নিজের হাতে', isCorrect: true },
      { text: 'গ্রহ-নক্ষত্রের', isCorrect: false },
      { text: 'শত্রুর', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'কোনটি ব্যক্তিত্বের শ্রী বৃদ্ধি করে?',
    answers: [
      { text: 'অলংকার', isCorrect: false },
      { text: 'সত্যনিষ্ঠা ও বিনয়', isCorrect: true },
      { text: 'মিথ্যা', isCorrect: false },
      { text: 'প্রসাধন', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মানুষের মনের একাগ্রতা নষ্ট করে কোনটি?',
    answers: [
      { text: 'পড়াশোনা', isCorrect: false },
      { text: 'অতিরিক্ত বিষয়াসক্তি ও চঞ্চলতা', isCorrect: true },
      { text: 'ব্যায়াম', isCorrect: false },
      { text: 'নির্জনতা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ভীরুতা ত্যাগ করার প্রধান উপায় কী?',
    answers: [
      { text: 'অস্ত্র রাখা', isCorrect: false },
      { text: 'অভীঃ বা নির্ভীক হওয়া', isCorrect: true },
      { text: 'পালিয়ে যাওয়া', isCorrect: false },
      { text: 'লুকিয়ে থাকা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্ব বিকাশের পথে বড় বাধা কোনটি?',
    answers: [
      { text: 'আলস্য ও জড়তা', isCorrect: true },
      { text: 'অর্থকষ্ট', isCorrect: false },
      { text: 'ভাষা', isCorrect: false },
      { text: 'দূরত্ব', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মানুষের মনে কিসের সম্ভাবনা লুকিয়ে আছে?',
    answers: [
      { text: 'অন্ধকারের', isCorrect: false },
      { text: 'অসীম দেবত্বের', isCorrect: true },
      { text: 'পশুর', isCorrect: false },
      { text: 'শয়তানের', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'চরিত্র কীভাবে গঠিত হয়?',
    answers: [
      { text: 'হঠাৎ করে', isCorrect: false },
      { text: 'বারংবার কাজের অভ্যাসের দ্বারা', isCorrect: true },
      { text: 'লটারিতে', isCorrect: false },
      { text: 'উপদেশের মাধ্যমে', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্ববান মানুষের প্রধান গুণ কী?',
    answers: [
      { text: 'অন্যের অনুকরণ', isCorrect: false },
      { text: 'নিজস্বতা ও আত্মনির্ভরশীলতা', isCorrect: true },
      { text: 'তোষামোদ করা', isCorrect: false },
      { text: 'পরশ্রীকাতরতা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'সেবাধর্ম ব্যক্তিত্বের ওপর কী প্রভাব ফেলে?',
    answers: [
      { text: 'মনকে ছোট করে', isCorrect: false },
      { text: 'হৃদয়কে প্রসারিত ও ব্যক্তিত্বকে উন্নত করে', isCorrect: true },
      { text: 'অহংকার বাড়ায়', isCorrect: false },
      { text: 'সময় নষ্ট করে', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'শিক্ষা যখন ব্যক্তিত্ব গঠন করে না, তখন তাকে কী বলে?',
    answers: [
      { text: 'মহৎ শিক্ষা', isCorrect: false },
      { text: 'কেবল তথ্য সংগ্রহ', isCorrect: true },
      { text: 'আধ্যাত্মিক শিক্ষা', isCorrect: false },
      { text: 'পূর্ণাঙ্গ শিক্ষা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'মানুষের অন্তর্নিহিত শক্তি প্রকাশের অন্তরায় কোনটি?',
    answers: [
      { text: 'অবিদ্যা বা অজ্ঞতা', isCorrect: true },
      { text: 'বিজ্ঞান', isCorrect: false },
      { text: 'যুক্তি', isCorrect: false },
      { text: 'গণিত', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'সফল হতে হলে মনকে কেমন করতে হবে?',
    answers: [
      { text: 'কাঁচের মতো ভঙ্গুর', isCorrect: false },
      { text: 'ইস্পাতের মতো দৃঢ়', isCorrect: true },
      { text: 'জলের মতো তরল', isCorrect: false },
      { text: 'বাতাসের মতো অস্থির', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'কার ব্যক্তিত্ব জগতকে আলোড়িত করে?',
    answers: [
      { text: 'ধার্মিক ভণ্ডদের', isCorrect: false },
      { text: 'যারা কথা ও কাজে এক', isCorrect: true },
      { text: 'যারা মিথ্যাবাদী', isCorrect: false },
      { text: 'যারা বিলাসী', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'বুদ্ধির স্থিরতাকে কী বলা হয়?',
    answers: [
      { text: 'মেধা', isCorrect: false },
      { text: 'প্রজ্ঞা বা ধীশক্তি', isCorrect: true },
      { text: 'চাতুর্য', isCorrect: false },
      { text: 'কল্পনা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: '"পাপী বলিয়ো না, দুর্বল বল"—এটি কার উক্তি?',
    answers: [
      { text: 'চৈতন্যদেব', isCorrect: false },
      { text: 'স্বামী বিবেকানন্দ', isCorrect: true },
      { text: 'রামমোহন রায়', isCorrect: false },
      { text: 'বঙ্কিমচন্দ্র', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্বের বিকাশে খাদ্যের প্রভাব কী?',
    answers: [
      { text: 'কোনো প্রভাব নেই', isCorrect: false },
      { text: 'সাত্ত্বিক খাদ্য মনকে শান্ত রাখে', isCorrect: true },
      { text: 'কেবল আমিষ খাদ্য প্রয়োজন', isCorrect: false },
      { text: 'ফাস্ট ফুড ভালো', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'কিসের মাধ্যমে মানুষ অমরত্ব লাভ করে?',
    answers: [
      { text: 'টাকার মাধ্যমে', isCorrect: false },
      { text: 'উন্নত চরিত্র ও নিঃস্বার্থ কর্মের মাধ্যমে', isCorrect: true },
      { text: 'শরীর রক্ষার মাধ্যমে', isCorrect: false },
      { text: 'ভ্রমণের মাধ্যমে', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'ব্যক্তিত্বের বিকাশ বইটির মূল লক্ষ্য কী?',
    answers: [
      { text: 'ইতিহাস জানানো', isCorrect: false },
      { text: 'মানুষের ঘুমন্ত আত্মাকে জাগানো', isCorrect: true },
      { text: 'কবিতা শেখানো', isCorrect: false },
      { text: 'রাজনীতি করা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'Bengali',
    questionText: 'জীবনের সার্থকতা কিসে?',
    answers: [
      { text: 'শুধু নিজের ভোগে', isCorrect: false },
      { text: 'ত্যাগে ও সেবায়', isCorrect: true },
      { text: 'অলসতায়', isCorrect: false },
      { text: 'ক্ষমতা দখলে', isCorrect: false },
    ],
  },
];
