import type { Question } from './types';

export const newEnglishLevel2Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Sure' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'অসম্ভব', isCorrect: false },
      { text: 'নিশ্চিত', isCorrect: true },
      { text: 'হয়তো', isCorrect: false },
      { text: 'কঠিন', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Table' শব্দটির IPA উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/\'teɪbl/', isCorrect: true },
      { text: '/\'tæksɪ/', isCorrect: false },
      { text: '/tiː/', isCorrect: false },
      { text: '/tɔːl/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Text' বলতে বইয়ের কোন অংশকে বোঝানো হয়েছে?",
    answers: [
      { text: 'প্রচ্ছদ', isCorrect: false },
      { text: 'নাম', isCorrect: false },
      { text: 'পাঠ বা লিখিত অংশ', isCorrect: true },
      { text: 'সূচিপত্র', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Their' শব্দটির অর্থ কী?",
    answers: [
      { text: 'আমাদের', isCorrect: false },
      { text: 'তোমার', isCorrect: false },
      { text: 'তাদের', isCorrect: true },
      { text: 'আমার', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Them' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'তারা', isCorrect: false },
      { text: 'তাদেরকে', isCorrect: true },
      { text: 'আমাদের', isCorrect: false },
      { text: 'সেখানে', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Ticket' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'বই', isCorrect: false },
      { text: 'টিকিট', isCorrect: true },
      { text: 'কলম', isCorrect: false },
      { text: 'টাকা', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Tired' শব্দটির অর্থ কী?",
    answers: [
      { text: 'শক্তিশালী', isCorrect: false },
      { text: 'ক্লান্ত', isCorrect: true },
      { text: 'খুশি', isCorrect: false },
      { text: 'রাগী', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Title' বলতে কোনো বইয়ের কী বোঝায়?",
    answers: [
      { text: 'দাম', isCorrect: false },
      { text: 'পাতা', isCorrect: false },
      { text: 'নাম বা খেতাব', isCorrect: true },
      { text: 'লেখক', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Town' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'গ্রাম', isCorrect: false },
      { text: 'শহর', isCorrect: true },
      { text: 'দেশ', isCorrect: false },
      { text: 'বিদেশ', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Train' (noun) বলতে কী বোঝায়?",
    answers: [
      { text: 'গাড়ি', isCorrect: false },
      { text: 'জাহাজ', isCorrect: false },
      { text: 'রেলগাড়ি', isCorrect: true },
      { text: 'বিমান', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Train' (verb) শব্দটির অর্থ কী?",
    answers: [
      { text: 'চালানো', isCorrect: false },
      { text: 'প্রশিক্ষণ দেওয়া', isCorrect: true },
      { text: 'কেনা', isCorrect: false },
      { text: 'দেখা', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Turn' শব্দটির অর্থ কী?",
    answers: [
      { text: 'থামা', isCorrect: false },
      { text: 'শুরু করা', isCorrect: false },
      { text: 'ঘুরানো বা ঘোরা', isCorrect: true },
      { text: 'বসা', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Wait' (verb) বলতে কী বোঝায়?",
    answers: [
      { text: 'চলে যাওয়া', isCorrect: false },
      { text: 'অপেক্ষা করা', isCorrect: true },
      { text: 'কথা বলা', isCorrect: false },
      { text: 'শোনা', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "/'taɪəd/ এটি কোন শব্দের IPA উচ্চারণ?",
    answers: [
      { text: 'Time', isCorrect: false },
      { text: 'Tired', isCorrect: true },
      { text: 'Title', isCorrect: false },
      { text: 'Town', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Their' এবং 'There'—এর মধ্যে 'There' বলতে কী বোঝায়?",
    answers: [
      { text: 'তাদের', isCorrect: false },
      { text: 'সেখানে', isCorrect: true },
      { text: 'তারা', isCorrect: false },
      { text: 'ওইটি', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Text' শব্দটির IPA রূপ কোনটি?",
    answers: [
      { text: '/tekst/', isCorrect: true },
      { text: '/teɪbl/', isCorrect: false },
      { text: '/tæn/', isCorrect: false },
      { text: '/tiːm/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Table' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/\'teɪbl/', isCorrect: true },
      { text: '/\'tæksɪ/', isCorrect: false },
      { text: '/tɔːl/', isCorrect: false },
      { text: '/tiːm/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "/'tæksɪ/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Text', isCorrect: false },
      { text: 'Taxi', isCorrect: true },
      { text: 'Ticket', isCorrect: false },
      { text: 'Town', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Think' শব্দটিতে ব্যবহৃত প্রথম প্রতীক /θ/ এর উচ্চারণ কেমন?",
    answers: [
      { text: 'ত-এর মতো', isCorrect: false },
      { text: 'থ-এর মতো', isCorrect: true },
      { text: 'দ-এর মতো', isCorrect: false },
      { text: 'শ-এর মতো', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Ticket' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/\'taɪm/', isCorrect: false },
      { text: '/\'tɪkɪt/', isCorrect: true },
      { text: '/\'taɪtl/', isCorrect: false },
      { text: '/\'taɪəd/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Time' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/taɪm/', isCorrect: true },
      { text: '/teɪm/', isCorrect: false },
      { text: '/tæm/', isCorrect: false },
      { text: '/tiːm/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "/'taɪəd/ এটি কোন শব্দের IPA রূপ?",
    answers: [
      { text: 'Title', isCorrect: false },
      { text: 'Town', isCorrect: false },
      { text: 'Tired', isCorrect: true },
      { text: 'Turn', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Title' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/\'taɪtl/', isCorrect: true },
      { text: '/\'teɪbl/', isCorrect: false },
      { text: '/\'tæksɪ/', isCorrect: false },
      { text: '/\'vɛri/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Town' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/taʊn/', isCorrect: true },
      { text: '/tɔːn/', isCorrect: false },
      { text: '/teɪn/', isCorrect: false },
      { text: '/tiːn/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Train' শব্দটিতে কোন Diphthong বা দ্বিস্বরধ্বনি ব্যবহৃত হয়েছে?",
    answers: [
      { text: '/aɪ/', isCorrect: false },
      { text: '/eɪ/', isCorrect: true },
      { text: '/ɔɪ/', isCorrect: false },
      { text: '/əʊ/', isCorrect: false },
    ],
  },
  {
    level: '0.2',
    subject: 'English',
    questionText: "'Turn' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/tɜː(r)n/', isCorrect: true },
      { text: '/tæn/', isCorrect: false },
      { text: '/tɔːn/', isCorrect: false },
      { text: '/tiːn/', isCorrect: false },
    ],
  },
];
