import type { Question } from './types';

export const newBengaliLevel1Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'প্রমথ চৌধুরী লাইব্রেরি সম্বন্ধে কথা বলার অধিকার পেয়েছেন কার দেওয়া সার্টিফিকেটের বলে?',
    answers: [
      { text: 'সুরেশচন্দ্র সমাজপতি', isCorrect: true },
      { text: 'বাৎস্যায়ন', isCorrect: false },
      { text: 'অস্কার ওয়াইল্ড', isCorrect: false },
      { text: 'আনাতোল ফ্রাঁস', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘বই পড়া’ প্রবন্ধটি প্রথম কোথায় পঠিত হয়েছিল?',
    answers: [
      { text: 'বঙ্গীয় সাহিত্য পরিষদ', isCorrect: false },
      { text: 'কটেজ লাইব্রেরি ও ভবানীপুর ইনস্টিটিউট', isCorrect: true },
      { text: 'শান্তিনিকেতন', isCorrect: false },
      { text: 'কলকাতা বিশ্ববিদ্যালয়', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'সাহিত্য পত্রে লেখককে কী বলে অভিহিত করা হয়েছিল?',
    answers: [
      { text: 'গ্রন্থকীট', isCorrect: false },
      { text: 'উদাসীন গ্রন্থকীট', isCorrect: true },
      { text: 'সাহিত্য বিশারদ', isCorrect: false },
      { text: 'বিদগ্ধ জন', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'এ যুগে সভ্য সমাজ সকালে উঠে কোন দুটি কাজ করে?',
    answers: [
      { text: 'ব্যায়াম ও চা-পান', isCorrect: false },
      { text: 'চা-পান ও সংবাদপত্র পাঠ', isCorrect: true },
      { text: 'বই পড়া ও প্রাতঃভ্রমণ', isCorrect: false },
      { text: 'পূজা ও সংবাদপত্র পাঠ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'সংবাদপত্র পাঠের ফলে মানুষের কীসে অরুচি হয়?',
    answers: [
      { text: 'আহারে', isCorrect: false },
      { text: 'কাব্যে', isCorrect: false },
      { text: 'সাহিত্যে', isCorrect: true },
      { text: 'কর্মে', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'লেখক এ যুগের মানুষের অবস্থাকে কীসের সাথে তুলনা করেছেন?',
    answers: [
      { text: 'শারীরিক অসুস্থতা', isCorrect: false },
      { text: 'মানসিক মন্দাগ্নি', isCorrect: true },
      { text: 'প্রবল আলস্য', isCorrect: false },
      { text: 'অশিক্ষা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'যে জাতি যত বেশি বই পড়ে, সে জাতি তত—',
    answers: [
      { text: 'ধনী', isCorrect: false },
      { text: 'সভ্য', isCorrect: true },
      { text: 'শক্তিশালী', isCorrect: false },
      { text: 'জ্ঞানী', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'নাগরিক সভ্যতার আদ্যোপান্ত বিবরণ কোন গ্রন্থে পাওয়া যায়?',
    answers: [
      { text: 'ন্যায়দর্শন', isCorrect: false },
      { text: 'কামসূত্র', isCorrect: true },
      { text: 'রামায়ণ', isCorrect: false },
      { text: 'মেঘদূত', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'কামসূত্রের রচয়িতা কে?',
    answers: [
      { text: 'জয়দেব', isCorrect: false },
      { text: 'সুরেশচন্দ্র', isCorrect: false },
      { text: 'বাৎস্যায়ন', isCorrect: true },
      { text: 'কৌটিল্য', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘প্রতিশয্যিকা’ শব্দের অর্থ কী?',
    answers: [
      { text: 'বালিশ', isCorrect: false },
      { text: 'বিছানা', isCorrect: false },
      { text: 'ক্ষুদ্র পর্যঙ্ক বা খাঁটিয়া', isCorrect: true },
      { text: 'টেবিল', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘বেদিকা’ শব্দের আধুনিক অর্থ লেখক কী অনুমান করেছেন?',
    answers: [
      { text: 'আলমারি', isCorrect: false },
      { text: 'টেবিল', isCorrect: true },
      { text: 'আসন', isCorrect: false },
      { text: 'ব্রাকেট', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘সিথকরণ্ডক’ কীসের কৌটা?',
    answers: [
      { text: 'সিন্দুর', isCorrect: false },
      { text: 'চন্দন', isCorrect: false },
      { text: 'মোম', isCorrect: true },
      { text: 'পাউডার', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘পতগ্রহ’ শব্দের অর্থ কী?',
    answers: [
      { text: 'পিকদানি', isCorrect: true },
      { text: 'ফুলদানি', isCorrect: false },
      { text: 'প্রদীপ', isCorrect: false },
      { text: 'ছাতা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'দেয়ালে হস্তিদন্তে কী ঝোলানো থাকত?',
    answers: [
      { text: 'ছবি', isCorrect: false },
      { text: 'তলোয়ার', isCorrect: false },
      { text: 'বীণা', isCorrect: true },
      { text: 'মালা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘নিচোল’ শব্দের প্রকৃত অর্থ কী?',
    answers: [
      { text: 'শাড়ি', isCorrect: false },
      { text: 'ওড়না', isCorrect: false },
      { text: 'গেলাপ বা ঘেরাটোপ', isCorrect: true },
      { text: 'রুমাল', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'পুরাকালে ছবি কীসের ওপর আঁকা হতো?',
    answers: [
      { text: 'কাপড়', isCorrect: false },
      { text: 'পাথর', isCorrect: false },
      { text: 'কাঠ', isCorrect: true },
      { text: 'কাগজ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘বর্তিকা সমুকের’ অর্থ কী?',
    answers: [
      { text: 'বই রাখার বাক্স', isCorrect: false },
      { text: 'তুলি ও রং রাখার বাক্স', isCorrect: true },
      { text: 'সিন্দুক', isCorrect: false },
      { text: 'কলমদানি', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'বীণাবাদন ও পুস্তকপঠনের মধ্যে কোনটি সহজতর?',
    answers: [
      { text: 'বীণাবাদন', isCorrect: false },
      { text: 'পুস্তকপঠন', isCorrect: true },
      { text: 'দুটিই সমান', isCorrect: false },
      { text: 'কোনটিই নয়', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'প্যারিসের নাগরিকেরা কোন লেখকের টাটকা বই না পড়লে লজ্জিত হন?',
    answers: [
      { text: 'কিপলিং', isCorrect: false },
      { text: 'অস্কার ওয়াইল্ড', isCorrect: false },
      { text: 'আনাতোল ফ্রাঁস', isCorrect: true },
      { text: 'শেক্সপিয়র', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'লন্ডনের নাগরিকের কাছে কার লেখা ‘অপাঠ্য’ বলে লেখক উল্লেখ করেছেন?',
    answers: [
      { text: 'কিপলিং', isCorrect: true },
      { text: 'আনাতোল ফ্রাঁস', isCorrect: false },
      { text: 'বাৎস্যায়ন', isCorrect: false },
      { text: 'সুরেশচন্দ্র', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'বিলেতের সেই ব্যারিস্টার মাসে কত টাকা রোজগার করতেন বলে জনরব ছিল?',
    answers: [
      { text: 'হাজার টাকা', isCorrect: false },
      { text: 'পাঁচ হাজার টাকা', isCorrect: false },
      { text: 'দশ-বিশ হাজার টাকা', isCorrect: true },
      { text: 'এক লক্ষ টাকা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'সেই ব্যারিস্টার কার বই পড়েননি বলে লজ্জিত হয়েছিলেন?',
    answers: [
      { text: 'রবীন্দ্রনাথের', isCorrect: false },
      { text: 'অস্কার ওয়াইল্ডের', isCorrect: true },
      { text: 'শরৎচন্দ্রের', isCorrect: false },
      { text: 'বঙ্কিমচন্দ্রের', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'সংস্কৃত ‘বিদগ্ধ’ শব্দের প্রতিশব্দ কী?',
    answers: [
      { text: 'সভ্য', isCorrect: false },
      { text: 'কালচারড (Cultured)', isCorrect: true },
      { text: 'পণ্ডিত', isCorrect: false },
      { text: 'শিক্ষিত', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'সংস্কৃত ভাষায় ‘গ্রাম্যতা’ ও ‘অসভ্যতা’ কী ধরণের শব্দ?',
    answers: [
      { text: 'বিপরীত শব্দ', isCorrect: false },
      { text: 'পর্যায়-শব্দ (Synonyms)', isCorrect: true },
      { text: 'পারিভাষিক শব্দ', isCorrect: false },
      { text: 'তদ্ভব শব্দ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘সংসার-বিষবৃক্ষের অমৃতাপম ফল’ কোনটি?',
    answers: [
      { text: 'ধন-সম্পদ', isCorrect: false },
      { text: 'পুণ্যকর্ম', isCorrect: false },
      { text: 'কাব্যামৃতের রস', isCorrect: true },
      { text: 'সংসার সুখ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'লেখক ঐতিহাসিক হওয়ার জন্য প্রথমত কী হতে বলেছেন?',
    answers: [
      { text: 'জ্ঞানী', isCorrect: false },
      { text: 'সত্যবাদী', isCorrect: false },
      { text: 'বর্তমানের প্রতি উদাসীন', isCorrect: true },
      { text: 'পরিশ্রমী', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'বর্বর জাতি ভোগ বলতে কী বোঝে?',
    answers: [
      { text: 'মানসিক আনন্দ', isCorrect: false },
      { text: 'দৈহিক প্রবৃত্তির চরিতার্থতা', isCorrect: true },
      { text: 'শিল্পচর্চা', isCorrect: false },
      { text: 'পরোপকার', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'কাব্যচর্চা মানুষকে নীতিবান না করলেও কী করে তোলে?',
    answers: [
      { text: 'রুচিবান', isCorrect: true },
      { text: 'ধনী', isCorrect: false },
      { text: 'দয়ালু', isCorrect: false },
      { text: 'উদ্ধত', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘মৃচ্ছকটিক’ নাটকের কোন চরিত্রের সাথে রাজশ্যালক শকারের তুলনা করা হয়েছে?',
    answers: [
      { text: 'বিদূষক', isCorrect: false },
      { text: 'বিট', isCorrect: true },
      { text: 'নায়ক', isCorrect: false },
      { text: 'চণ্ডাল', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'এ যুগের সভ্যতা কেমন হতে চাচ্ছে?',
    answers: [
      { text: 'অ্যারিস্টোক্র্যাটিক', isCorrect: false },
      { text: 'ডেমোক্র্যাটিক', isCorrect: true },
      { text: 'স্বৈরতান্ত্রিক', isCorrect: false },
      { text: 'সামন্ততান্ত্রিক', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'এ যুগের কবিরা কাব্যে কী করেন?',
    answers: [
      { text: 'সমাজ সংস্কার', isCorrect: false },
      { text: 'আত্মপ্রকাশ', isCorrect: true },
      { text: 'রাজার স্তুতি', isCorrect: false },
      { text: 'ধর্ম প্রচার', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'ডেমোক্র্যাসির গুরুরা সকলকে কী করতে চেয়েছিলেন?',
    answers: [
      { text: 'ধনী', isCorrect: false },
      { text: 'শিক্ষিত', isCorrect: false },
      { text: 'সমান', isCorrect: true },
      { text: 'ধার্মিক', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘ব্যায়ামই সংক্রামক, স্বাস্থ্য নয়’—এর প্রেক্ষিতে লেখক আমাদের শিক্ষিত সমাজের দৃষ্টি কোথায় বলেছেন?',
    answers: [
      { text: 'জ্ঞানের ওপর', isCorrect: false },
      { text: 'ধর্মের ওপর', isCorrect: false },
      { text: 'অর্থের ওপর', isCorrect: true },
      { text: 'সেবার ওপর', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'জ্ঞানের ভাণ্ডার পূর্ণ না হলে কীসের ভাণ্ডার পূর্ণ হয় না?',
    answers: [
      { text: 'স্বাস্থ্যের', isCorrect: false },
      { text: 'ধনের', isCorrect: true },
      { text: 'শক্তির', isCorrect: false },
      { text: 'সম্মানের', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'মানুষের পুরো মনটির সাক্ষাৎ কোথায় পাওয়া যায়?',
    answers: [
      { text: 'বিজ্ঞানে', isCorrect: false },
      { text: 'দর্শনে', isCorrect: false },
      { text: 'সাহিত্যে', isCorrect: true },
      { text: 'ইতিহাসে', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'দর্শন চর্চার জন্য লেখকের মতে উপযুক্ত স্থান কোনটি?',
    answers: [
      { text: 'গুহা', isCorrect: true },
      { text: 'মন্দির', isCorrect: false },
      { text: 'লাইব্রেরি', isCorrect: false },
      { text: 'জাদুঘর', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'বিজ্ঞান চর্চার জন্য কোথায় যাওয়া উচিত?',
    answers: [
      { text: 'কারখানা', isCorrect: false },
      { text: 'চিড়িয়াখানা', isCorrect: false },
      { text: 'জাদুঘর', isCorrect: true },
      { text: 'গবেষণাগার', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'লাইব্রেরির সার্থকতা কার চাইতে বেশি বলে লেখক মনে করেন?',
    answers: [
      { text: 'মন্দিরের', isCorrect: false },
      { text: 'হাসপাতালের', isCorrect: false },
      { text: 'স্কুল-কলেজের', isCorrect: true },
      { text: 'বাজারের', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: 'লেখকের মতে সুশিক্ষিত লোক মাত্রই—',
    answers: [
      { text: 'উচ্চশিক্ষিত', isCorrect: false },
      { text: 'স্বশিক্ষিত', isCorrect: true },
      { text: 'নীতিবান', isCorrect: false },
      { text: 'ধনবান', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'Bengali',
    questionText: '‘উদাসীন গ্রন্থকীট’ কথাটির অর্থ কী?',
    answers: [
      { text: 'যে পোকা বই কাটে', isCorrect: false },
      { text: 'যে ব্যক্তি লাইব্রেরিতে সময় কাটায়', isCorrect: true },
      { text: 'যে বই পড়তে জানে না', isCorrect: false },
      { text: 'যে জ্ঞানহীন', isCorrect: false },
    ],
  },
];
