import type { Question } from './types';

export const newEnglishLevel8Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zeal' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'ঘৃণা', isCorrect: false },
      { text: 'প্রবল আগ্রহ বা উৎসাহ', isCorrect: true },
      { text: 'অলসতা', isCorrect: false },
      { text: 'ভয়', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/jiːld/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত (IPA)?",
    answers: [
      { text: 'Yield', isCorrect: true },
      { text: 'Yell', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zone', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zombie' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈzɒmbi/', isCorrect: true },
      { text: '/ˈzəʊn/', isCorrect: false },
      { text: '/ˈziːl/', isCorrect: false },
      { text: '/ˈjel/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yell' শব্দটির সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'চুপিচুপি বলা', isCorrect: false },
      { text: 'চিৎকার করা', isCorrect: true },
      { text: 'হাসা', isCorrect: false },
      { text: 'কান্না করা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈze lət/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Zealot', isCorrect: true },
      { text: 'Zealous', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zone', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zone' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'পাহাড়', isCorrect: false },
      { text: 'অঞ্চল বা এলাকা', isCorrect: true },
      { text: 'সমুদ্র', isCorrect: false },
      { text: 'আকাশ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zealous' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈze ləs/', isCorrect: true },
      { text: '/ˈze lət/', isCorrect: false },
      { text: '/ziːl/', isCorrect: false },
      { text: '/ˈzɒm bi/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈjɑː hu/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Yahoo', isCorrect: true },
      { text: 'Yacht', isCorrect: false },
      { text: 'Yield', isCorrect: false },
      { text: 'Yell', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yacht' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'ছোট জাহাজ বা প্রমোদতরি', isCorrect: true },
      { text: 'বাস', isCorrect: false },
      { text: 'রিকশা', isCorrect: false },
      { text: 'উড়োজাহাজ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yield' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jiːld/', isCorrect: true },
      { text: '/jel/', isCorrect: false },
      { text: '/ziːl/', isCorrect: false },
      { text: '/zəʊn/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zealot' শব্দটির অর্থ কী?",
    answers: [
      { text: 'অতি গোঁড়া বা ধর্মান্ধ ব্যক্তি', isCorrect: true },
      { text: 'উদার ব্যক্তি', isCorrect: false },
      { text: 'বিজ্ঞানী', isCorrect: false },
      { text: 'চিকিৎসক', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/zuː/ এটি নিচের কোন স্থানের সঠিক IPA?",
    answers: [
      { text: 'Zoo', isCorrect: true },
      { text: 'Zone', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zip', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yahoo' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈjɑːhu/', isCorrect: true },
      { text: '/jɒt/', isCorrect: false },
      { text: '/jiːld/', isCorrect: false },
      { text: '/ˈzelət/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zoo' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'চিড়িয়াখানা', isCorrect: true },
      { text: 'বিদ্যালয়', isCorrect: false },
      { text: 'বাজার', isCorrect: false },
      { text: 'বাগান', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/jel/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Yell', isCorrect: true },
      { text: 'Yield', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Yacht', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zealous' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'অতি উৎসাহী', isCorrect: true },
      { text: 'অত্যন্ত রাগী', isCorrect: false },
      { text: 'খুব দুঃখিত', isCorrect: false },
      { text: 'ভীতু', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yacht' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jɒt/', isCorrect: true },
      { text: '/jɑːt/', isCorrect: false },
      { text: '/jiːld/', isCorrect: false },
      { text: '/jel/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/zəʊn/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Zone', isCorrect: true },
      { text: 'Zoo', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zip', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yield' বলতে কী বোঝায়?",
    answers: [
      { text: 'বশ্যতা স্বীকার করা / উৎপাদন', isCorrect: true },
      { text: 'অস্বীকার করা', isCorrect: false },
      { text: 'ধ্বংস করা', isCorrect: false },
      { text: 'চুরি করা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zeal' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ziːl/', isCorrect: true },
      { text: '/ˈzeləs/', isCorrect: false },
      { text: '/ˈzelət/', isCorrect: false },
      { text: '/zuː/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zombie' এর অর্থ কী?",
    answers: [
      { text: 'মৃতদেহ যা পুনরায় জীবিত হয়েছে', isCorrect: true },
      { text: 'একজন বীর', isCorrect: false },
      { text: 'মহাকাশচারী', isCorrect: false },
      { text: 'শিক্ষক', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈziːl/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Zeal', isCorrect: true },
      { text: 'Zealot', isCorrect: false },
      { text: 'Zealous', isCorrect: false },
      { text: 'Zone', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yahoo' শব্দটির অর্থ কী?",
    answers: [
      { text: 'অসভ্য বা বন্য ব্যক্তি', isCorrect: true },
      { text: 'অত্যন্ত ভদ্র লোক', isCorrect: false },
      { text: 'রাজা', isCorrect: false },
      { text: 'বন্ধু', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yell' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/jel/', isCorrect: true },
      { text: '/jiːld/', isCorrect: false },
      { text: '/jɒt/', isCorrect: false },
      { text: '/zuː/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ɪn ˈsep tə bl/ এটি কোন শব্দের IPA (ফাইল থেকে)?",
    answers: [
      { text: 'Inacceptable', isCorrect: true },
      { text: 'Innocent', isCorrect: false },
      { text: 'Inside', isCorrect: false },
      { text: 'Income', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Acceptable' শব্দটির বিপরীত শব্দ কোনটি হতে পারে (A2/B2 লেভেল অনুযায়ী)?",
    answers: [
      { text: 'Unacceptable', isCorrect: true },
      { text: 'Accept', isCorrect: false },
      { text: 'Achieving', isCorrect: false },
      { text: 'Actual', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈæktɪvɪst/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Activist', isCorrect: true },
      { text: 'Activity', isCorrect: false },
      { text: 'Activate', isCorrect: false },
      { text: 'Actor', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Achievement' শব্দটির সঠিক অর্থ কী?",
    answers: [
      { text: 'অর্জন', isCorrect: true },
      { text: 'বর্জন', isCorrect: false },
      { text: 'পরাজয়', isCorrect: false },
      { text: 'লজ্জা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ə ˈtʃiːv/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Achieve', isCorrect: true },
      { text: 'Achievement', isCorrect: false },
      { text: 'Acid', isCorrect: false },
      { text: 'Acre', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Ability' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/əˈbɪləti/', isCorrect: true },
      { text: '/ˈeɪbl/', isCorrect: false },
      { text: '/ˈæsɪd/', isCorrect: false },
      { text: '/ækt/', isCorrect: false },
    ],
  },
];
