import type { Question } from './types';

export const newEnglishLevel7Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Abundant' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'অভাব', isCorrect: false },
      { text: 'প্রচুর/বিপুল', isCorrect: true },
      { text: 'সামান্য', isCorrect: false },
      { text: 'উজ্জ্বল', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/əˈbæn dən/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত (IPA)?",
    answers: [
      { text: 'Abandon', isCorrect: true },
      { text: 'Abundant', isCorrect: false },
      { text: 'Ability', isCorrect: false },
      { text: 'Absence', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Accurate' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈæ kjə rət/', isCorrect: true },
      { text: '/ək ˈsept/', isCorrect: false },
      { text: '/ə ˈkjuːt/', isCorrect: false },
      { text: '/ə ˈtʃiːv/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Brilliant' শব্দটির বাংলা অর্থ কী?",
    answers: [
      { text: 'সাহসী', isCorrect: false },
      { text: 'মেধাবী/উজ্জ্বল', isCorrect: true },
      { text: 'ধূর্ত', isCorrect: false },
      { text: 'অলস', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ɪˈnʌf/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Enough', isCorrect: true },
      { text: 'Energy', isCorrect: false },
      { text: 'Entry', isCorrect: false },
      { text: 'Enjoy', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Exaggerate' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'সংক্ষিপ্ত করা', isCorrect: false },
      { text: 'বাড়িয়ে বলা', isCorrect: true },
      { text: 'বর্ণনা করা', isCorrect: false },
      { text: 'গোপন করা', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Knowledge' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈnɒl ɪdʒ/', isCorrect: true },
      { text: '/nəʊ/', isCorrect: false },
      { text: '/ˈknɒ lɪdʒ/', isCorrect: false },
      { text: '/ˈnəʊ lɪdʒ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˌriː ə ˈʃʊə(r)/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Reassure', isCorrect: true },
      { text: 'Reason', isCorrect: false },
      { text: 'Recent', isCorrect: false },
      { text: 'Record', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Insufficient' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'পর্যাপ্ত', isCorrect: false },
      { text: 'অপ্রাসঙ্গিক', isCorrect: false },
      { text: 'অপর্যাপ্ত', isCorrect: true },
      { text: 'অদৃশ্য', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Wrist' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/rɪst/', isCorrect: true },
      { text: '/rɪstɪ/', isCorrect: false },
      { text: '/wrɪst/', isCorrect: false },
      { text: '/raɪst/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Yearn' শব্দটির অর্থ কী?",
    answers: [
      { text: 'উপার্জন করা', isCorrect: false },
      { text: 'ব্যাকুল আকাঙ্ক্ষা করা', isCorrect: true },
      { text: 'ঘৃণা করা', isCorrect: false },
      { text: 'ভুলে যাওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˈjɒ ɡət/ এটি নিচের কোন খাবারের সঠিক IPA?",
    answers: [
      { text: 'Yogurt', isCorrect: true },
      { text: 'Yellow', isCorrect: false },
      { text: 'Yeast', isCorrect: false },
      { text: 'Yawn', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Worthy' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɜː(r) ði/', isCorrect: true },
      { text: '/ˈwɜː r θi/', isCorrect: false },
      { text: '/wɜː(r) θ/', isCorrect: false },
      { text: '/ˈwɜː r kɪŋ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Irrelevant' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'প্রাসঙ্গিক', isCorrect: false },
      { text: 'অপ্রাসঙ্গিক', isCorrect: true },
      { text: 'অকেজো', isCorrect: false },
      { text: 'অবৈধ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ɪ ˈkwɪp mənt/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Equipment', isCorrect: true },
      { text: 'Equal', isCorrect: false },
      { text: 'Entry', isCorrect: false },
      { text: 'Event', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Fragile' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'মজবুত', isCorrect: false },
      { text: 'ভঙ্গুর', isCorrect: true },
      { text: 'পাতলা', isCorrect: false },
      { text: 'দামি', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Drought' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/draʊt/', isCorrect: true },
      { text: '/drɔːt/', isCorrect: false },
      { text: '/drʌf/', isCorrect: false },
      { text: '/draʊθ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˌkɒm prə ˈmaɪz/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Compromise', isCorrect: true },
      { text: 'Comprise', isCorrect: false },
      { text: 'Company', isCorrect: false },
      { text: 'Compare', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Wrinkle' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'ভাঁজ বা কুঁচকানো', isCorrect: true },
      { text: 'সোজা করা', isCorrect: false },
      { text: 'পরিষ্কার', isCorrect: false },
      { text: 'উজ্জ্বল', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Youth' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/juːθ/', isCorrect: true },
      { text: '/jʊθ/', isCorrect: false },
      { text: '/juːs/', isCorrect: false },
      { text: '/jʌŋ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Obvious' শব্দটির বাংলা অর্থ কী?",
    answers: [
      { text: 'অস্পষ্ট', isCorrect: false },
      { text: 'স্পষ্ট/প্রতীয়মান', isCorrect: true },
      { text: 'কঠিন', isCorrect: false },
      { text: 'সাধারণ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˈpɜː(r) tʃəs/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Purchase', isCorrect: true },
      { text: 'Purpose', isCorrect: false },
      { text: 'Perfect', isCorrect: false },
      { text: 'Person', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Queue' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/kjuː/', isCorrect: true },
      { text: '/kwɪ/', isCorrect: false },
      { text: '/kwe/', isCorrect: false },
      { text: '/kjuːi/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Sufficient' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'পর্যাপ্ত', isCorrect: true },
      { text: 'অতিরিক্ত', isCorrect: false },
      { text: 'সামান্য', isCorrect: false },
      { text: 'অভাব', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ə ˈpɪə rəns/ এটি কোন শব্দের IPA?",
    answers: [
      { text: 'Appearance', isCorrect: true },
      { text: 'Appoint', isCorrect: false },
      { text: 'Approve', isCorrect: false },
      { text: 'Appeal', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Leisure' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'কাজ', isCorrect: false },
      { text: 'অবসর', isCorrect: true },
      { text: 'আনন্দ', isCorrect: false },
      { text: 'ভ্রমণ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˈmɪs tʃɪf/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Mischief', isCorrect: true },
      { text: 'Machine', isCorrect: false },
      { text: 'Message', isCorrect: false },
      { text: 'Music', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Precious' শব্দটির সঠিক অর্থ কী?",
    answers: [
      { text: 'সস্তা', isCorrect: false },
      { text: 'মূল্যবান', isCorrect: true },
      { text: 'পুরাতন', isCorrect: false },
      { text: 'সাধারণ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˌvɒl ən ˈtɪə(r)/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Volunteer', isCorrect: true },
      { text: 'Volume', isCorrect: false },
      { text: 'Victory', isCorrect: false },
      { text: 'Village', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Yard' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jɑː(r)d/', isCorrect: true },
      { text: '/jærd/', isCorrect: false },
      { text: '/jɜːrd/', isCorrect: false },
      { text: '/jɔːrd/', isCorrect: false },
    ],
  },
];
