
import type { Question } from './types';

export const newEnglishLevel9Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Abridge' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'বাড়িয়ে বলা', isCorrect: false },
      { text: 'সংক্ষেপ করা', isCorrect: true },
      { text: 'ধ্বংস করা', isCorrect: false },
      { text: 'গ্রহণ করা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Agile' শব্দটির সঠিক অর্থ কী?",
    answers: [
      { text: 'অলস', isCorrect: false },
      { text: 'সাবলীল ও চটপটে', isCorrect: true },
      { text: 'খুব লম্বা', isCorrect: false },
      { text: 'স্থির', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Altitude' শব্দটির সঠিক বাংলা প্রতিশব্দ কোনটি?",
    answers: [
      { text: 'গভীরতা', isCorrect: false },
      { text: 'উচ্চতা', isCorrect: true },
      { text: 'প্রশস্থতা', isCorrect: false },
      { text: 'ওজন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Anthropology' বলতে কী বোঝায়?",
    answers: [
      { text: 'নৃবিজ্ঞান', isCorrect: true },
      { text: 'প্রাণিবিজ্ঞান', isCorrect: false },
      { text: 'জ্যোতির্বিজ্ঞান', isCorrect: false },
      { text: 'ভূতত্ত্ব', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Apace' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'ধীর গতিতে', isCorrect: false },
      { text: 'দ্রুত গতিতে', isCorrect: true },
      { text: 'মাঝেমধ্যে', isCorrect: false },
      { text: 'কখনোই নয়', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Apathy' শব্দটির সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'গভীর মনোযোগ', isCorrect: false },
      { text: 'প্রবল উৎসাহ', isCorrect: false },
      { text: 'উদাসীনতা বা অনাগ্রহ', isCorrect: true },
      { text: 'সহানুভূতি', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Aptitude' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'স্বাভাবিক দক্ষতা বা প্রবণতা', isCorrect: true },
      { text: 'উচ্চতা', isCorrect: false },
      { text: 'ঘ্রাণশক্তি', isCorrect: false },
      { text: 'শ্রবনশক্তি', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Arctic' শব্দটির বাংলা অর্থ কী?",
    answers: [
      { text: 'মরুভূমি অঞ্চল', isCorrect: false },
      { text: 'উত্তর মেরু বা সুমেরু অঞ্চল', isCorrect: true },
      { text: 'গ্রীষ্মমন্ডল', isCorrect: false },
      { text: 'পাহাড়ী অঞ্চল', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Assay' শব্দটির অর্থ কী?",
    answers: [
      { text: 'প্রবন্ধ লেখা', isCorrect: false },
      { text: 'বিশুদ্ধতা পরীক্ষা করা', isCorrect: true },
      { text: 'সাহায্য করা', isCorrect: false },
      { text: 'আক্রমণ করা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Assorted' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'একই রকমের', isCorrect: false },
      { text: 'বিভিন্ন রকমের', isCorrect: true },
      { text: 'পচে যাওয়া', isCorrect: false },
      { text: 'নতুন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/əˈbrɪdʒ/ এটি কোন শব্দের সঠিক উচ্চারণ (IPA)?",
    answers: [
      { text: 'Abridge', isCorrect: true },
      { text: 'Average', isCorrect: false },
      { text: 'Advantage', isCorrect: false },
      { text: 'Arrange', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ədˈmɪʃn/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Admission', isCorrect: true },
      { text: 'Addition', isCorrect: false },
      { text: 'Action', isCorrect: false },
      { text: 'Ambition', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈædʒaɪl/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Angel', isCorrect: false },
      { text: 'Agile', isCorrect: true },
      { text: 'Again', isCorrect: false },
      { text: 'Agent', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæltɪtjuːd/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Attitude', isCorrect: false },
      { text: 'Altitude', isCorrect: true },
      { text: 'Aptitude', isCorrect: false },
      { text: 'Amplitude', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæŋɡlɪŋ/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Angling', isCorrect: true },
      { text: 'Angry', isCorrect: false },
      { text: 'Angle', isCorrect: false },
      { text: 'Ankle', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈænɪmɪzəm/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Animal', isCorrect: false },
      { text: 'Animism', isCorrect: true },
      { text: 'Animation', isCorrect: false },
      { text: 'Anoint', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/əˈpeɪs/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Space', isCorrect: false },
      { text: 'Apace', isCorrect: true },
      { text: 'Apple', isCorrect: false },
      { text: 'Apply', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæpəθi/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Apathy', isCorrect: true },
      { text: 'Ability', isCorrect: false },
      { text: 'Apply', isCorrect: false },
      { text: 'Anyway', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæptɪtjuːd/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Attitude', isCorrect: false },
      { text: 'Altitude', isCorrect: false },
      { text: 'Aptitude', isCorrect: true },
      { text: 'Arctic', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/əˈseɪ/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Essay', isCorrect: false },
      { text: 'Assay', isCorrect: true },
      { text: 'Away', isCorrect: false },
      { text: 'Always', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Witch' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/wɪtʃ/', isCorrect: true },
      { text: '/wɒtʃ/', isCorrect: false },
      { text: '/wɪʃ/', isCorrect: false },
      { text: '/wɪθ/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Withhold' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/wɪðˈhəʊld/', isCorrect: true },
      { text: '/wɪθˈaʊt/', isCorrect: false },
      { text: '/wɪðˈɪn/', isCorrect: false },
      { text: '/wɪðˈdrɔː/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Womb' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/wuːm/', isCorrect: true },
      { text: '/wɒm/', isCorrect: false },
      { text: '/wʌm/', isCorrect: false },
      { text: '/wuːnd/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Yelp' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jelp/', isCorrect: true },
      { text: '/jelpɪŋ/', isCorrect: false },
      { text: '/help/', isCorrect: false },
      { text: '/self/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Willful' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɪlfl/', isCorrect: true },
      { text: /ˈwɪlɪŋ/, isCorrect: false },
      { text: /ˈwaɪli/, isCorrect: false },
      { text: /wɪl/, isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Willy-nilly' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˌwɪli ˈnɪli/', isCorrect: true },
      { text: '/ˈwɪli/', isCorrect: false },
      { text: '/ˈnɪli/', isCorrect: false },
      { text: '/ˌwɪli ˈwɪli/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Wily' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwaɪli/', isCorrect: true },
      { text: '/ˈwɪli/', isCorrect: false },
      { text: '/ˈwaɪf/', isCorrect: false },
      { text: '/ˈwɪndɪ/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Winnow' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɪnəʊ/', isCorrect: true },
      { text: '/ˈwɪndəʊ/', isCorrect: false },
      { text: '/ˈwɪnə(r)/', isCorrect: false },
      { text: '/ˈwɪnɪŋ/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Winsome' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɪnsəm/', isCorrect: true },
      { text: '/ˈwɪntə(r)/', isCorrect: false },
      { text: '/wɪn/', isCorrect: false },
      { text: '/ˈwelkəm/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Anoint' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/əˈnɔɪnt/', isCorrect: true },
      { text: '/əˈnaʊns/', isCorrect: false },
      { text: /ˈænədʌɪz/, isCorrect: false },
      { text: /ˈæntiruːm/, isCorrect: false },
    ],
  },
];
