import type { Question } from './types';

export const newEnglishLevel4Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Each' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/iːtʃ/', isCorrect: true },
      { text: '/itʃ/', isCorrect: false },
      { text: '/iːs/', isCorrect: false },
      { text: '/iːk/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Our' শব্দের সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/aʊə(r)/', isCorrect: false },
      { text: '/ɔː(r)/', isCorrect: false },
      { text: 'উভয়ই', isCorrect: true },
      { text: 'কোনটিই নয়', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Verdant' শব্দটির অর্থ কী?",
    answers: [
      { text: 'নীল', isCorrect: false },
      { text: 'সতেজ ও সবুজ', isCorrect: true },
      { text: 'লাল', isCorrect: false },
      { text: 'কালো', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "/ðeə(r)/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'There', isCorrect: false },
      { text: 'Their', isCorrect: true },
      { text: 'They', isCorrect: false },
      { text: 'Them', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Mine' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/maɪ/', isCorrect: false },
      { text: '/maɪn/', isCorrect: true },
      { text: '/mi/', isCorrect: false },
      { text: '/meɪn/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Incarnadine' শব্দের অর্থ কী?",
    answers: [
      { text: 'রক্তিম বা লাল', isCorrect: true },
      { text: 'সবুজ', isCorrect: false },
      { text: 'হলুদ', isCorrect: false },
      { text: 'বেগুনি', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Us' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/ʌs/', isCorrect: false },
      { text: '/əs/', isCorrect: true },
      { text: '/juːs/', isCorrect: false },
      { text: '/uːs/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Verdure' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈvɜːr djə(r)/', isCorrect: true },
      { text: '/ˈvɜːr dnt/', isCorrect: false },
      { text: '/vɜːr/', isCorrect: false },
      { text: '/ˈvɜːr dʒə/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'They' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ðeɪ/', isCorrect: true },
      { text: '/deɪ/', isCorrect: false },
      { text: '/ðæt/', isCorrect: false },
      { text: '/ðiːz/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Whose' শব্দের সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/huːz/', isCorrect: true },
      { text: '/huːm/', isCorrect: false },
      { text: '/huː/', isCorrect: false },
      { text: '/haʊ/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Their' শব্দের অর্থ কী?",
    answers: [
      { text: 'তারা', isCorrect: false },
      { text: 'তাদের', isCorrect: true },
      { text: 'আমাদের', isCorrect: false },
      { text: 'আমার', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "/mi/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'My', isCorrect: false },
      { text: 'Me', isCorrect: true },
      { text: 'Mine', isCorrect: false },
      { text: 'Many', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'These' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ðiːz/', isCorrect: true },
      { text: '/ðɪs/', isCorrect: false },
      { text: '/ðæt/', isCorrect: false },
      { text: '/ðeɪ/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Dun' শব্দটির অর্থ কী?",
    answers: [
      { text: 'সাদা', isCorrect: false },
      { text: 'পিঙ্গল বা ধূসর', isCorrect: true },
      { text: 'লাল', isCorrect: false },
      { text: 'নীল', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "/hɪm/ এটি কোন শব্দের IPA রূপ?",
    answers: [
      { text: 'He', isCorrect: false },
      { text: 'Him', isCorrect: true },
      { text: 'His', isCorrect: false },
      { text: 'Her', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'None' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/nʌn/', isCorrect: true },
      { text: '/nəʊn/', isCorrect: false },
      { text: '/nəʊ/', isCorrect: false },
      { text: '/nʌt/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'You' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ju/', isCorrect: true },
      { text: '/jʊ/', isCorrect: false },
      { text: '/uː/', isCorrect: false },
      { text: '/jɔː(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Its' শব্দটির উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ɪt/', isCorrect: false },
      { text: '/ɪts/', isCorrect: true },
      { text: '/ɪz/', isCorrect: false },
      { text: '/ɪn/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Whom' শব্দের সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/huːm/', isCorrect: true },
      { text: '/huːz/', isCorrect: false },
      { text: '/huː/', isCorrect: false },
      { text: '/huːv/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Verdant' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈvɜːr djə(r)/', isCorrect: false },
      { text: '/ˈvɜːr dnt/', isCorrect: true },
      { text: '/ˈvɜːrdnt/', isCorrect: false },
      { text: '/vɜːr dnt/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Who' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/huː/', isCorrect: true },
      { text: '/haʊ/', isCorrect: false },
      { text: '/huːm/', isCorrect: false },
      { text: '/huːz/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'I' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/aɪ/', isCorrect: true },
      { text: '/eɪ/', isCorrect: false },
      { text: '/ɔɪ/', isCorrect: false },
      { text: '/ɪ/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Her' এবং 'His' শব্দের সাধারণ উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/hə(r)/ এবং /hɪz/', isCorrect: true },
      { text: '/hɪm/ এবং /hi/', isCorrect: false },
      { text: '/hi/ এবং /ʃi/', isCorrect: false },
      { text: '/ðeə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Mine' অর্থ কী?",
    answers: [
      { text: 'আমার', isCorrect: true },
      { text: 'আমাকে', isCorrect: false },
      { text: 'আমি', isCorrect: false },
      { text: 'আমরা', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'They' অর্থ কী?",
    answers: [
      { text: 'তারা', isCorrect: true },
      { text: 'তাদের', isCorrect: false },
      { text: 'আমাদের', isCorrect: false },
      { text: 'তোমাদের', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'This' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ðɪs/', isCorrect: true },
      { text: '/ðiːz/', isCorrect: false },
      { text: '/ðæt/', isCorrect: false },
      { text: '/ðeɪ/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'That' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/ðæt/', isCorrect: true },
      { text: '/ðɪs/', isCorrect: false },
      { text: '/ðen/', isCorrect: false },
      { text: '/ðeə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'Me' শব্দটির অর্থ কী?",
    answers: [
      { text: 'আমি', isCorrect: false },
      { text: 'আমার', isCorrect: false },
      { text: 'আমাকে', isCorrect: true },
      { text: 'আমরা', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'What' শব্দটির উচ্চারণ সংকেত কী?",
    answers: [
      { text: '/wɒt/', isCorrect: true },
      { text: '/huː/', isCorrect: false },
      { text: '/haʊ/', isCorrect: false },
      { text: '/wen/', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'English',
    questionText: "'We' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/wi/', isCorrect: true },
      { text: '/mi/', isCorrect: false },
      { text: '/hi/', isCorrect: false },
      { text: '/ʃi/', isCorrect: false },
    ],
  },
];
