
import type { Question } from './types';

export const newBengaliLevel9Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: "'অর্জুন মণ্ডল' গল্পের লেখকের নাম কী?",
    answers: [
      { text: 'রবীন্দ্রনাথ ঠাকুর', isCorrect: false },
      { text: 'বনফুল', isCorrect: true },
      { text: 'শরৎচন্দ্র চট্টোপাধ্যায়', isCorrect: false },
      { text: 'মানিক বন্দ্যোপাধ্যায়', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'গল্পের শুরুতে বীরেনবাবুর বাড়িতে কে কড়া নেড়েছিলেন?',
    answers: [
      { text: 'চিতুয়া', isCorrect: false },
      { text: 'অর্জুন মণ্ডল', isCorrect: true },
      { text: 'এক অচেনা যুবক', isCorrect: false },
      { text: 'বীরেনবাবুর বাবা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডলের চেহারার বর্ণনা অনুযায়ী তিনি কেমন ছিলেন?',
    answers: [
      { text: 'দীর্ঘকায়', isCorrect: false },
      { text: 'খর্বকায়', isCorrect: true },
      { text: 'স্থূলকায়', isCorrect: false },
      { text: 'অত্যন্ত সুঠাম', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন কাকার গায়ে কী রঙের কোট ছিল?',
    answers: [
      { text: 'কালো পশমি', isCorrect: false },
      { text: 'নীল রেশমি', isCorrect: false },
      { text: 'আজানুলম্বিত খদ্দরের', isCorrect: true },
      { text: 'লাল সুতি', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল বীরেনবাবুর বাড়িতে কোন সময় এসেছিলেন?',
    answers: [
      { text: 'ভরা দুপুরে', isCorrect: false },
      { text: 'ভোরবেলা', isCorrect: false },
      { text: 'শীতকালের গভীর রাতে', isCorrect: true },
      { text: 'গোধূলি বেলায়', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডলের চিঠি কেন বীরেনবাবুর কাছে পৌঁছায়নি?',
    answers: [
      { text: 'পোস্ট অফিস হারানোয়', isCorrect: false },
      { text: 'চিতুয়া পোস্ট করেনি বলে', isCorrect: true },
      { text: 'ঠিকানা ভুল ছিল', isCorrect: false },
      { text: 'বৃষ্টির জন্য', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল কোথায় যাচ্ছিলেন?',
    answers: [
      { text: 'বিদেশ', isCorrect: false },
      { text: 'ব্যবসা করতে', isCorrect: false },
      { text: 'তীর্থে', isCorrect: true },
      { text: 'মেয়ের বাড়ি', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: '"জীবনটা ভুল করতে করতেই কাটল বীরেনবাবু"—উক্তিটি কার?',
    answers: [
      { text: 'বীরেনবাবুর', isCorrect: false },
      { text: 'চিতুয়ার', isCorrect: false },
      { text: 'অর্জুন মণ্ডলের', isCorrect: true },
      { text: 'লেখকের স্ত্রীর', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল বীরেনবাবুকে কী বলে সম্বোধন করতেন?',
    answers: [
      { text: 'স্যার', isCorrect: false },
      { text: 'বীরেনবাবু', isCorrect: true },
      { text: 'খোকা', isCorrect: false },
      { text: 'দাদাভাই', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল কেন শহরে এসেছেন?',
    answers: [
      { text: 'বেড়াতে', isCorrect: false },
      { text: 'তীর্থের জিনিসপত্র কিনতে', isCorrect: true },
      { text: 'ডাক্তার দেখাতে', isCorrect: false },
      { text: 'জমি কিনতে', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'চিতুয়া কে ছিলেন?',
    answers: [
      { text: 'অর্জুন মণ্ডলের ছেলে', isCorrect: false },
      { text: 'অর্জুন মণ্ডলের চাকর বা কর্মচারী', isCorrect: true },
      { text: 'বীরেনবাবুর বন্ধু', isCorrect: false },
      { text: 'ডাকপিয়ন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল কীসের জন্য একটি সিন্দুক বানাচ্ছিলেন?',
    answers: [
      { text: 'টাকা রাখতে', isCorrect: false },
      { text: 'জীবনের শেষ সার্থকতা বা জেদ হিসেবে', isCorrect: true },
      { text: 'চাল রাখতে', isCorrect: false },
      { text: 'ছেলেকে দিতে', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'সিন্দুকটি মজবুত করার জন্য অর্জুন কাকা কোণে কোণে কী দিয়েছিলেন?',
    answers: [
      { text: 'সোনার পাত', isCorrect: false },
      { text: 'লোহার পাত', isCorrect: true },
      { text: 'তামা', isCorrect: false },
      { text: 'অ্যালুমিনিয়াম', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'সিন্দুকটির ভেতর কীসের আস্তরণ দেওয়া হয়েছিল?',
    answers: [
      { text: 'মখমল', isCorrect: false },
      { text: 'খদ্দর', isCorrect: false },
      { text: 'মিল্টন কাপড়', isCorrect: true },
      { text: 'রেশম', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডলের মতে, তার জীবনে কোন জিনিসটি নিখুঁত হয়েছে?',
    answers: [
      { text: 'সিন্দুকটি', isCorrect: true },
      { text: 'তার সংসার', isCorrect: false },
      { text: 'তার তীর্থযাত্রা', isCorrect: false },
      { text: 'তার বড় ছেলের স্বভাব', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: '"শালা ডাকু"—অর্জুন মণ্ডল এই গালিটি কার উদ্দেশ্যে ব্যবহার করেছিলেন?',
    answers: [
      { text: 'ডাকপিয়ন', isCorrect: false },
      { text: 'বীরেনবাবু', isCorrect: false },
      { text: 'চিতুয়া', isCorrect: true },
      { text: 'পুলিশ', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'সিন্দুকের সৌন্দর্য বৃদ্ধির জন্য অর্জুন কাকা কী কিনে এনেছিলেন?',
    answers: [
      { text: 'রূপোর ফুল', isCorrect: false },
      { text: 'ডুমো ডুমো পেরেক', isCorrect: true },
      { text: 'ঝালর', isCorrect: false },
      { text: 'রঙ', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডলের ভুরু কেমন ছিল?',
    answers: [
      { text: 'কালো', isCorrect: false },
      { text: 'পাক ধরা', isCorrect: true },
      { text: 'পাতলা', isCorrect: false },
      { text: 'খুব ঘন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'লেখকের বর্ণনায় অর্জুন মণ্ডলের সামনে কয়টি দাঁত ছিল না?',
    answers: [
      { text: 'একটি', isCorrect: false },
      { text: 'গোটা দুই', isCorrect: true },
      { text: 'সবকটি', isCorrect: false },
      { text: 'দাঁত সব ঠিক ছিল', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল মাঝে মাঝে কথাবার্তায় কোন ধরনের ক্রিয়াপদ ব্যবহার করতেন?',
    answers: [
      { text: 'চলিত', isCorrect: false },
      { text: 'শুদ্ধ বা সাধু', isCorrect: true },
      { text: 'আঞ্চলিক', isCorrect: false },
      { text: 'ইংরেজি', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল সিন্দুকটি নিয়ে কার কাছে জেদ ধরেছিলেন?',
    answers: [
      { text: 'বীরেনবাবুর কাছে', isCorrect: false },
      { text: 'মিস্ত্রির কাছে', isCorrect: false },
      { text: 'নিজের মনের কাছে', isCorrect: true },
      { text: 'স্ত্রীর কাছে', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল সিন্দুকটিকে কী করতে চেয়েছিলেন?',
    answers: [
      { text: 'বিক্রি করতে', isCorrect: false },
      { text: 'নিখুঁত করতে', isCorrect: true },
      { text: 'বড় করতে', isCorrect: false },
      { text: 'হালকা করতে', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'শীতের রাতে বীরেনবাবু কিসের শব্দে ঘুম থেকে উঠে বসলেন?',
    answers: [
      { text: 'বজ্রপাতের', isCorrect: false },
      { text: 'কড়া নাড়ার', isCorrect: true },
      { text: 'চোর আসার', isCorrect: false },
      { text: 'ফোনের ঘণ্টার', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডলের চোখ কেমন ছিল?',
    answers: [
      { text: 'উজ্জ্বল', isCorrect: false },
      { text: 'নিষ্প্রভ', isCorrect: true },
      { text: 'টকটকে লাল', isCorrect: false },
      { text: 'টানা টানা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: '"ভুল, ভুলু এ জীবনটা ভুল করতে করতেই কাটল"—এই আক্ষেপ কেন?',
    answers: [
      { text: 'টাকা হারানোয়', isCorrect: false },
      { text: 'সিন্দুক না হওয়ায়', isCorrect: false },
      { text: 'জীবনভর ব্যর্থতার অভিজ্ঞতায়', isCorrect: true },
      { text: 'ভুল পথে যাওয়ায়', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডলের মাথার সম্মুখভাগ কেমন ছিল?',
    answers: [
      { text: 'ঘন কালো চুল', isCorrect: false },
      { text: 'কেশ-বিরল', isCorrect: true },
      { text: 'সাদা চুলে ঢাকা', isCorrect: false },
      { text: 'পাগড়ি পরা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'গল্পের প্রেক্ষাপট কোন ঋতুর?',
    answers: [
      { text: 'গ্রীষ্ম', isCorrect: false },
      { text: 'বর্ষা', isCorrect: false },
      { text: 'শরৎ', isCorrect: false },
      { text: 'শীত', isCorrect: true },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডল বীরেনবাবুর কী হতেন?',
    answers: [
      { text: 'নিজের কাকা', isCorrect: false },
      { text: 'পরিচিত বা প্রতিবেশী (অর্জুনকাকা সম্বোধন)', isCorrect: true },
      { text: 'মামা', isCorrect: false },
      { text: 'দাদু', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: '"হয় নি কিছু। তোমার কাছে খবর না দিয়ে আসবার জোরও আমার আছে"—বক্তা কে?',
    answers: [
      { text: 'বীরেন', isCorrect: false },
      { text: 'চিতুয়া', isCorrect: false },
      { text: 'অর্জুন মণ্ডল', isCorrect: true },
      { text: 'অর্জুন মণ্ডলের স্ত্রী', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'Bengali',
    questionText: 'অর্জুন মণ্ডলের পুরো নাম কী?',
    answers: [
      { text: 'অর্জুন সিংহ', isCorrect: false },
      { text: 'অর্জুন মণ্ডল', isCorrect: true },
      { text: 'অর্জুন দাস', isCorrect: false },
      { text: 'অর্জুন ঘোষ', isCorrect: false },
    ],
  },
];
