import type { Question } from './types';

export const newBengaliLevel6Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'মানুষের জীবনের সব সাফল্যের মূল চাবিকাঠি কী?',
    answers: [
      { text: 'প্রচুর অর্থ', isCorrect: false },
      { text: 'আত্মবিশ্বাস ও সঠিক চিন্তাভাবনা', isCorrect: true },
      { text: 'উচ্চ বংশমর্যাদা', isCorrect: false },
      { text: 'অন্যের সাহায্য', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: "'মন প্রকৌশল' বলতে লেখক প্রধানত কী বুঝিয়েছেন?",
    answers: [
      { text: 'ইঞ্জিনিয়ারিং পড়া', isCorrect: false },
      { text: 'মনের সুশৃঙ্খল নিয়ন্ত্রণ ও গঠন', isCorrect: true },
      { text: 'বেশি করে স্বপ্ন দেখা', isCorrect: false },
      { text: 'স্মৃতিশক্তি বাড়ানো', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'ব্যর্থতাকে সফলতার কী হিসেবে দেখা উচিত?',
    answers: [
      { text: 'শেষ সীমানা', isCorrect: false },
      { text: 'ভাগ্যের লিখন', isCorrect: false },
      { text: 'শিক্ষার ধাপ বা সিঁড়ি', isCorrect: true },
      { text: 'সময়ের অপচয়', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'নেতিবাচক চিন্তা মনের ওপর কী প্রভাব ফেলে?',
    answers: [
      { text: 'সাহস বাড়ায়', isCorrect: false },
      { text: 'আত্মবিশ্বাস কমিয়ে দেয়', isCorrect: true },
      { text: 'কর্মক্ষমতা বাড়ায়', isCorrect: false },
      { text: 'কোনো প্রভাব ফেলে না', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'মানুষের সবচেয়ে বড় শত্রু কে?',
    answers: [
      { text: 'প্রতিবেশী', isCorrect: false },
      { text: 'নিজের ভেতরের ভয় ও সংশয়', isCorrect: true },
      { text: 'অভাব', isCorrect: false },
      { text: 'সময়', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'লক্ষ্য অর্জনে কোন বিষয়টি সবচেয়ে বেশি জরুরি?',
    answers: [
      { text: 'শুধু কল্পনা করা', isCorrect: false },
      { text: 'সুনির্দিষ্ট পরিকল্পনা', isCorrect: true },
      { text: 'ভাগ্যের ওপর নির্ভর করা', isCorrect: false },
      { text: 'কঠোর পরিশ্রম ছাড়াই চিন্তা', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'বড় স্বপ্ন দেখার সাহস ও দূরদর্শিতাকে কী বলা হয়?',
    answers: [
      { text: 'বিলাসিতা', isCorrect: false },
      { text: 'রূপকল্প (Vision)', isCorrect: true },
      { text: 'অলীক কল্পনা', isCorrect: false },
      { text: 'অহংকার', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'সময়ের সঠিক ও পরিকল্পিত ব্যবহারকে কী বলা হয়?',
    answers: [
      { text: 'সময় ব্যবস্থাপনা', isCorrect: true },
      { text: 'সময় কাটানো', isCorrect: false },
      { text: 'রুটিন মাফিক চলা', isCorrect: false },
      { text: 'কৃপণতা', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'আলস্য কাটাতে সবচেয়ে কার্যকর উপায় কোনটি?',
    answers: [
      { text: 'ঘুমানো', isCorrect: false },
      { text: 'ছোট ছোট লক্ষ্য নির্ধারণ', isCorrect: true },
      { text: 'সব কাজ জমিয়ে রাখা', isCorrect: false },
      { text: 'কালকের জন্য অপেক্ষা', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'আমাদের অবচেতন মন (Subconscious Mind) কীভাবে কাজ করে?',
    answers: [
      { text: 'যুক্তি দিয়ে', isCorrect: false },
      { text: 'বিশ্বাসের ওপর ভিত্তি করে', isCorrect: true },
      { text: 'গাণিতিক নিয়মে', isCorrect: false },
      { text: 'ঘুমের ঘোরে', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'ইতিবাচক শব্দ বা উক্তি বারবার বলাকে কী বলে?',
    answers: [
      { text: 'চিৎকার', isCorrect: false },
      { text: 'মিথ্যে বলা', isCorrect: false },
      { text: 'অ্যাফারমেশন (Affirmation)', isCorrect: true },
      { text: 'আবৃত্তি', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'সফল হতে হলে আগে কোনটির পরিবর্তন প্রয়োজন?',
    answers: [
      { text: 'পোশাকের', isCorrect: false },
      { text: 'নিজের দৃষ্টিভঙ্গির', isCorrect: true },
      { text: 'বাসস্থানের', isCorrect: false },
      { text: 'বন্ধুর', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'মানুষের চরিত্রের মেরুদণ্ড কোনটি?',
    answers: [
      { text: 'উচ্চশিক্ষা', isCorrect: false },
      { text: 'সম্পদ', isCorrect: false },
      { text: 'সততা ও নৈতিকতা', isCorrect: true },
      { text: 'গায়ের জোর', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'সৃজনশীলতা বৃদ্ধির প্রধান উপায় কী?',
    answers: [
      { text: 'চুপচাপ থাকা', isCorrect: false },
      { text: 'অজানাকে জানার আগ্রহ', isCorrect: true },
      { text: 'অনুকরণ করা', isCorrect: false },
      { text: 'কাজ এড়িয়ে চলা', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'ধ্যানের (Meditation) প্রধান উপকারিতা কী?',
    answers: [
      { text: 'শারীরিক উচ্চতা বৃদ্ধি', isCorrect: false },
      { text: 'মানসিক স্থিরতা ও মনোযোগ বৃদ্ধি', isCorrect: true },
      { text: 'স্বপ্ন দেখা কমানো', isCorrect: false },
      { text: 'ক্ষুধা বাড়ানো', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'কোনো ভালো কাজ শুরু করার সঠিক সময় কোনটি?',
    answers: [
      { text: 'আগামী মাস', isCorrect: false },
      { text: 'শুভ দিন দেখে', isCorrect: false },
      { text: 'এখনই বা বর্তমান সময়', isCorrect: true },
      { text: 'অবসর সময়ে', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'অন্যের সমালোচনাকে কীভাবে গ্রহণ করা উচিত?',
    answers: [
      { text: 'রেগে গিয়ে', isCorrect: false },
      { text: 'গঠনমূলকভাবে ও ধৈর্যের সাথে', isCorrect: true },
      { text: 'পাল্টা আক্রমণ করে', isCorrect: false },
      { text: 'এড়িয়ে চলে', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'সফল ব্যক্তিরা দিনের শুরুতে সাধারণত কী করেন?',
    answers: [
      { text: 'দেরি করে ঘুম থেকে ওঠেন', isCorrect: false },
      { text: 'গুরুত্বপূর্ণ কাজের তালিকা করেন', isCorrect: true },
      { text: 'সোশ্যাল মিডিয়া দেখেন', isCorrect: false },
      { text: 'অন্যের সমালোচনা করেন', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'নিজের আবেগকে নিয়ন্ত্রণ ও বুঝতে পারার ক্ষমতাকে কী বলে?',
    answers: [
      { text: 'চালাকি', isCorrect: false },
      { text: 'ইমোশনাল ইন্টেলিজেন্স', isCorrect: true },
      { text: 'উদাসীনতা', isCorrect: false },
      { text: 'কাঠিন্য', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'জীবনে ঝুঁকি (Risk) নেওয়া কেন প্রয়োজন?',
    answers: [
      { text: 'বিপদে পড়ার জন্য', isCorrect: false },
      { text: 'নতুন কিছু শেখার ও বড় হওয়ার জন্য', isCorrect: true },
      { text: 'টাকা নষ্ট করার জন্য', isCorrect: false },
      { text: 'সাহসিকতা দেখানোর জন্য', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: "'কমফোর্ট জোন' (আরামদায়ক অবস্থা) থেকে বের হওয়া কেন জরুরি?",
    answers: [
      { text: 'বিপদে পড়ার জন্য', isCorrect: false },
      { text: 'ব্যক্তিগত উন্নয়ন ও সাফল্যের জন্য', isCorrect: true },
      { text: 'ঘর থেকে বের হওয়ার জন্য', isCorrect: false },
      { text: 'ব্যায়াম করার জন্য', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'ধৈর্য ও অধ্যবসায় মূলত কিসের লক্ষণ?',
    answers: [
      { text: 'দুর্বলতার', isCorrect: false },
      { text: 'অলসতার', isCorrect: false },
      { text: 'মানসিক শক্তি ও স্থিরতার', isCorrect: true },
      { text: 'দারিদ্র্যের', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'সুশৃঙ্খল জীবনযাপনের প্রথম ও প্রধান ধাপ কোনটি?',
    answers: [
      { text: 'বেশি করে খাওয়া', isCorrect: false },
      { text: 'ভোরে ঘুম থেকে ওঠা', isCorrect: true },
      { text: 'রাত জেগে কাজ করা', isCorrect: false },
      { text: 'টিভি দেখা', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'পরশ্রীকাতরতা বা হিংসা মনের কী ক্ষতি করে?',
    answers: [
      { text: 'বুদ্ধি বাড়ায়', isCorrect: false },
      { text: 'সৃজনশীলতা ও শান্তি নষ্ট করে', isCorrect: true },
      { text: 'ধনী হতে সাহায্য করে', isCorrect: false },
      { text: 'স্মৃতিশক্তি বাড়ায়', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'নিজের মনের ওপর পূর্ণ নিয়ন্ত্রণ থাকলে কী অর্জন সম্ভব?',
    answers: [
      { text: 'ঐশ্বরিক ক্ষমতা', isCorrect: false },
      { text: 'যেকোনো সুনির্দিষ্ট ও কঠিন লক্ষ্য', isCorrect: true },
      { text: 'মানুষের মন পড়া', isCorrect: false },
      { text: 'অদৃশ্য হওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'নিয়মিত বই পড়ার অভ্যাস মানুষকে কী প্রদান করে?',
    answers: [
      { text: 'চোখের ক্লান্তি', isCorrect: false },
      { text: 'জ্ঞানের গভীরতা ও নতুন দৃষ্টিভঙ্গি', isCorrect: true },
      { text: 'কেবল পরীক্ষার ফল', isCorrect: false },
      { text: 'অহংকার', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: "'কৃতজ্ঞতা' (Gratitude) প্রকাশের ফলে মনে কীসের সৃষ্টি হয়?",
    answers: [
      { text: 'ভয়', isCorrect: false },
      { text: 'প্রশান্তি ও ইতিবাচকতা', isCorrect: true },
      { text: 'অশান্তি', isCorrect: false },
      { text: 'অতৃপ্তি', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'অন্যের ওপর অতিরিক্ত নির্ভরশীলতা কমানোর নাম কী?',
    answers: [
      { text: 'একাকীত্ব', isCorrect: false },
      { text: 'আত্মনির্ভরশীলতা', isCorrect: true },
      { text: 'স্বার্থপরতা', isCorrect: false },
      { text: 'উদাসীনতা', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'ব্যর্থতা থেকে শিক্ষা নিয়ে আবার ঘুরে দাঁড়ানোকে কী বলে?',
    answers: [
      { text: 'বোকামি', isCorrect: false },
      { text: 'রেজিলিয়েন্স (Resilience)', isCorrect: true },
      { text: 'একগুঁয়েমি', isCorrect: false },
      { text: 'হার মেনে নেওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'লক্ষ্য ঠিক করার পর সাফল্যের জন্য কোনটির প্রয়োজন সবচেয়ে বেশি?',
    answers: [
      { text: 'বিরতি নেওয়া', isCorrect: false },
      { text: 'ধারাবাহিকতা ও প্রচেষ্টা', isCorrect: true },
      { text: 'ভাগ্যের দোহাই দেওয়া', isCorrect: false },
      { text: 'মানুষকে জানানো', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'শারীরিক সুস্থতা ও ব্যায়াম মনের ওপর কেমন প্রভাব ফেলে?',
    answers: [
      { text: 'মনকে ক্লান্ত করে', isCorrect: false },
      { text: 'মনকে প্রফুল্ল ও কর্মক্ষম রাখে', isCorrect: true },
      { text: 'চিন্তাশক্তি কমিয়ে দেয়', isCorrect: false },
      { text: 'অলসতা বাড়ায়', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'আপনার জীবনের ও মনের প্রধান স্থপতি কে?',
    answers: [
      { text: 'সমাজ', isCorrect: false },
      { text: 'আপনি নিজে', isCorrect: true },
      { text: 'প্রতিবেশী', isCorrect: false },
      { text: 'নিয়তি', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'অতিরিক্ত দুশ্চিন্তা বা ওভারথিংকিং করলে কী হয়?',
    answers: [
      { text: 'বুদ্ধি বাড়ে', isCorrect: false },
      { text: 'সিদ্ধান্ত নেওয়ার ক্ষমতা লোপ পায়', isCorrect: true },
      { text: 'সমস্যার সমাধান হয়', isCorrect: false },
      { text: 'স্মৃতিশক্তি বাড়ে', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'কার্যকর যোগাযোগের জন্য কথা বলার চেয়ে বেশি কী করা প্রয়োজন?',
    answers: [
      { text: 'উচ্চস্বরে কথা বলা', isCorrect: false },
      { text: 'মনোযোগ দিয়ে অন্যের কথা শোনা', isCorrect: true },
      { text: 'চুপ করে থাকা', isCorrect: false },
      { text: 'তর্ক করা', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: "সফলতার 'শর্টকাট' বা সংক্ষিপ্ত রাস্তা কোনটি?",
    answers: [
      { text: 'লটারি', isCorrect: false },
      { text: 'সফলতার আসলে কোনো শর্টকাট নেই', isCorrect: true },
      { text: 'অন্যের নকল করা', isCorrect: false },
      { text: 'ফাঁকি দেওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'নেতিবাচক মানুষের সঙ্গ ত্যাগ করা কেন প্রয়োজন?',
    answers: [
      { text: 'নিজেকে বড় দেখানোর জন্য', isCorrect: false },
      { text: 'নিজের স্বপ্ন ও মানসিক স্বাস্থ্য বাঁচাতে', isCorrect: true },
      { text: 'ঝগড়া এড়াতে', isCorrect: false },
      { text: 'একা থাকার জন্য', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'ক্ষমা করার গুণটি মানুষের মনে কী ধরনের অনুভূতি এনে দেয়?',
    answers: [
      { text: 'অপরাধবোধ', isCorrect: false },
      { text: 'মানসিক মুক্তি ও হালকা ভাব', isCorrect: true },
      { text: 'ক্রোধ', isCorrect: false },
      { text: 'পরাজয়ের গ্লানি', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'কোনো কাজের প্রতি তীব্র একাগ্রতা বা ফোকাসকে কী বলা হয়?',
    answers: [
      { text: 'বিভ্রম', isCorrect: false },
      { text: 'ধ্রুব লক্ষ্য বা ফোকাস', isCorrect: true },
      { text: 'একঘেয়েমি', isCorrect: false },
      { text: 'জাদুকরী শক্তি', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'আত্মমর্যাদাবোধ (Self-esteem) কেন প্রয়োজন?',
    answers: [
      { text: 'অন্যকে ছোট করার জন্য', isCorrect: false },
      { text: 'নিজের সঠিক মূল্যায়ন নিজে করার জন্য', isCorrect: true },
      { text: 'অহংকার করার জন্য', isCorrect: false },
      { text: 'পদবী পাওয়ার জন্য', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'Bengali',
    questionText: 'জীবন গড়ার চূড়ান্ত বা আসল ফরমুলা কোনটি?',
    answers: [
      { text: 'কেবল প্রার্থনা করা', isCorrect: false },
      { text: 'নিরন্তর চেষ্টা, ধৈর্য ও সঠিক কর্মপন্থা', isCorrect: true },
      { text: 'সুযোগের অপেক্ষায় বসে থাকা', isCorrect: false },
      { text: 'অন্যের সাফল্যে ঈর্ষা করা', isCorrect: false },
    ],
  },
];
