import type { Question } from './types';

export const newBengaliLevel5Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'সরোজ আচার্যের মতে, বই পড়ার কাজটা আমরা কেমনভাবে করি?',
    answers: [
      { text: 'কেবল পেশা হিসেবে', isCorrect: false },
      { text: 'নেশা ও পেশা হিসেবে', isCorrect: true },
      { text: 'অনিচ্ছাসত্ত্বেও', isCorrect: false },
      { text: 'দায়বদ্ধতা থেকে', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'বই না-পড়ুয়াদের প্রতি আমাদের মনোভাব কী হওয়া উচিত বলে লেখক মনে করেন?',
    answers: [
      { text: 'অবজ্ঞা', isCorrect: false },
      { text: 'ঘৃণা', isCorrect: false },
      { text: 'অনুকম্পা', isCorrect: true },
      { text: 'রাগ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'অর্বাচীন' শব্দের অর্থ কী?",
    answers: [
      { text: 'চালাক', isCorrect: false },
      { text: 'মূর্খ বা অপরিণত বুদ্ধি', isCorrect: true },
      { text: 'বৃদ্ধ', isCorrect: false },
      { text: 'মহৎ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'লেখক বই পড়ার নেশাকে কোন নেশার চেয়ে ভালো বলেছেন?',
    answers: [
      { text: 'ভ্রমণের নেশা', isCorrect: false },
      { text: 'খাবারের নেশা', isCorrect: false },
      { text: 'সিনেমার নেশা', isCorrect: true },
      { text: 'আড্ডার নেশা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'অরন্তুদ' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'সুখদায়ক', isCorrect: false },
      { text: 'মর্মভেদী', isCorrect: true },
      { text: 'ভয়ংকর', isCorrect: false },
      { text: 'অদ্ভুত', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'বার্নার্ড শ-এর মতে কোনটি মৃত্যু সমতুল্য?',
    answers: [
      { text: 'দারিদ্র্য', isCorrect: false },
      { text: 'রোগ', isCorrect: false },
      { text: 'মূঢ়তা', isCorrect: true },
      { text: 'অলসতা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'খদ্যোত' বলতে কী বোঝায়?",
    answers: [
      { text: 'জোনাকি পোকা', isCorrect: true },
      { text: 'সূর্য', isCorrect: false },
      { text: 'নক্ষত্র', isCorrect: false },
      { text: 'উল্কা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "লেখক 'জাত-পড়ুয়া' কাদের বলেছেন?",
    answers: [
      { text: 'যারা শুধু কবিতা পড়ে', isCorrect: false },
      { text: 'যারা নির্বিচারে সবই পড়েন', isCorrect: true },
      { text: 'যারা শুধু আধুনিক বই পড়ে', isCorrect: false },
      { text: 'যারা পরীক্ষার জন্য পড়ে', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'কুঞ্ঝটিকা' শব্দের অর্থ কী?",
    answers: [
      { text: 'বৃষ্টি', isCorrect: false },
      { text: 'ঝড়', isCorrect: false },
      { text: 'কুয়াশা', isCorrect: true },
      { text: 'মেঘ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'বই পড়ার জগতে লেখকদের বৈচিত্র্যকে লেখক কিসের সাথে তুলনা করেছেন?',
    answers: [
      { text: 'আকাশের নক্ষত্র', isCorrect: false },
      { text: 'সমুদ্রের ঢেউ', isCorrect: false },
      { text: 'রাস্তার অজস্র লোক', isCorrect: true },
      { text: 'বনের গাছপালা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'পেলব' শব্দের অর্থ কী?",
    answers: [
      { text: 'শক্ত', isCorrect: false },
      { text: 'কোমল বা মৃদু', isCorrect: true },
      { text: 'নীল', isCorrect: false },
      { text: 'বড়', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'খাঁটি বই-পড়ুয়ারা কাদের ওপর নির্ভর করে বই বিচার করে?',
    answers: [
      { text: 'সমালোচক', isCorrect: false },
      { text: 'নিজের অনুভূতি', isCorrect: true },
      { text: 'বিজ্ঞজন', isCorrect: false },
      { text: 'বিজ্ঞাপন', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'তক্ষক' শব্দের অর্থ কী?",
    answers: [
      { text: 'সাপুড়ে', isCorrect: false },
      { text: 'ছুতার', isCorrect: true },
      { text: 'কামার', isCorrect: false },
      { text: 'কুমার', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "লেখক শশধর দত্তের সাথে কতক্ষণ 'রহস্য শিকার' করা স্বাস্থ্যকর বলেছেন?",
    answers: [
      { text: '১ ঘণ্টা', isCorrect: false },
      { text: '৫ ঘণ্টা', isCorrect: false },
      { text: '২/৪ ঘণ্টা', isCorrect: true },
      { text: 'সারাদিন', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'উত্তাল' বা 'আসার' শব্দের অর্থ কী?",
    answers: [
      { text: 'মৃদু বাতাস', isCorrect: false },
      { text: 'প্রবল বৃষ্টিপাত', isCorrect: true },
      { text: 'রোদ্র', isCorrect: false },
      { text: 'কুয়াশা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "বই পড়া নিয়ে বিজ্ঞজনের উপদেশ অনুযায়ী কোন ধরণের বই 'চিবিয়ে হজম' করতে হয়?",
    answers: [
      { text: 'সব বই', isCorrect: false },
      { text: 'নির্বাচিত কিছু বই', isCorrect: true },
      { text: 'গল্পের বই', isCorrect: false },
      { text: 'অনুবাদের বই', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'বিরাগী' শব্দটির অর্থ হলো—",
    answers: [
      { text: 'রাগী', isCorrect: false },
      { text: 'উদাসীন', isCorrect: true },
      { text: 'সংসারী', isCorrect: false },
      { text: 'লোভী', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'কার ভাষায় সাধারণ পাঠক এক হিসেবে অসাধারণ?',
    answers: [
      { text: 'রবীন্দ্রনাথ ঠাকুর', isCorrect: false },
      { text: 'বার্নার্ড শ', isCorrect: false },
      { text: 'ভার্জিনিয়া উলফ', isCorrect: true },
      { text: 'আগাথা ক্রিস্টি', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'পনস' শব্দের অর্থ কী?",
    answers: [
      { text: 'আম', isCorrect: false },
      { text: 'কাঁঠাল', isCorrect: true },
      { text: 'লিচু', isCorrect: false },
      { text: 'কলা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'জীবনের একঘেয়েমি থেকে মুক্তি পেতে লেখক কোন ধরণের বইকে প্রেরণা বলেছেন?',
    answers: [
      { text: 'প্রবন্ধ', isCorrect: false },
      { text: 'নাটক', isCorrect: false },
      { text: 'কবিতা', isCorrect: true },
      { text: 'রাজনীতি', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'মৃগয়া' শব্দের অর্থ কী?",
    answers: [
      { text: 'পাখি ধরা', isCorrect: false },
      { text: 'হরিণ শিকার', isCorrect: true },
      { text: 'মাছ ধরা', isCorrect: false },
      { text: 'বাঘ মারা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'বই পড়াকে লেখক কিসের ধারার সাথে তুলনা করেছেন?',
    answers: [
      { text: 'ঝরনা', isCorrect: false },
      { text: 'নদী', isCorrect: false },
      { text: 'বৃষ্টির সহস্র ধারা', isCorrect: true },
      { text: 'সমুদ্রের স্রোত', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'কপর্দকহীন' মানে কী?",
    answers: [
      { text: 'ধনী', isCorrect: false },
      { text: 'নিঃস্ব', isCorrect: true },
      { text: 'কৃপণ', isCorrect: false },
      { text: 'বুদ্ধিমান', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'কার পরে বাংলায় অনেক কবিতা লেখা হয়েছে বলে প্রবন্ধে উল্লেখ আছে?',
    answers: [
      { text: 'নজরুল', isCorrect: false },
      { text: 'জীবনানন্দ', isCorrect: false },
      { text: 'রবীন্দ্রনাথ', isCorrect: true },
      { text: 'মধুসূদন', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'শুক্তি' শব্দের অর্থ কী?",
    answers: [
      { text: 'মুক্তা', isCorrect: false },
      { text: 'ঝিনুক', isCorrect: true },
      { text: 'শাঁখ', isCorrect: false },
      { text: 'কাঁকড়া', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'লেখক কেন বিদেশী বই পড়ার কথা বলেছেন?',
    answers: [
      { text: 'পৃথিবী আজ একাকার বলে', isCorrect: true },
      { text: 'জ্ঞান বাড়াতে', isCorrect: false },
      { text: 'ফ্যাশন করতে', isCorrect: false },
      { text: 'সময় কাটাতে', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'প্রতীকধর্মী' শব্দের অর্থ হলো—",
    answers: [
      { text: 'দেবতাপূজা', isCorrect: false },
      { text: 'নিদর্শন জ্ঞাপক', isCorrect: true },
      { text: 'ধার্মিক', isCorrect: false },
      { text: 'কাল্পনিক', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'বই পড়ুয়াদের মধ্যে কারা দলে ভারী?',
    answers: [
      { text: 'সমালোচকরা', isCorrect: false },
      { text: 'বিজ্ঞজনরা', isCorrect: false },
      { text: 'সাধারণ পাঠকরা', isCorrect: true },
      { text: 'আধুনিক পাঠকরা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'রোজনামচা' বলতে কী বোঝায়?",
    answers: [
      { text: 'ইতিহাস', isCorrect: false },
      { text: 'দিনলিপি', isCorrect: true },
      { text: 'হিসাবের খাতা', isCorrect: false },
      { text: 'খবরের কাগজ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'কোন ধরণের বই পড়া সংস্কারের দাসত্ব বা মূঢ়তা?',
    answers: [
      { text: 'সব ধরণের', isCorrect: false },
      { text: 'শুধুমাত্র বিশেষ ধরণের', isCorrect: true },
      { text: 'বিদেশী বই', isCorrect: false },
      { text: 'অনুবাদের বই', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'উপাধান' শব্দের অর্থ কী?",
    answers: [
      { text: 'চাদর', isCorrect: false },
      { text: 'বালিশ', isCorrect: true },
      { text: 'লেপ', isCorrect: false },
      { text: 'তোশক', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: '"পাখী সব করে রব রাতি পোহাইল"— এই লাইনটি কোন সময়ের পড়ার কথা মনে করায়?',
    answers: [
      { text: 'যৌবন', isCorrect: false },
      { text: 'বার্ধক্য', isCorrect: false },
      { text: 'ছেলেবেলা', isCorrect: true },
      { text: 'স্কুল জীবন', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'গুবাক' শব্দের অর্থ কী?",
    answers: [
      { text: 'নারিকেল', isCorrect: false },
      { text: 'সুপারি', isCorrect: true },
      { text: 'আমলকী', isCorrect: false },
      { text: 'হরতকী', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'ফ্যাশনের দাবি পূরণ করতেও বই পড়া লোকসান নয় কেন?',
    answers: [
      { text: 'বই কেনা হয় বলে', isCorrect: false },
      { text: 'পাতা উল্টাতে উল্টাতে ভালো লাগা তৈরি হয়', isCorrect: true },
      { text: 'জ্ঞান বাড়ে বলে', isCorrect: false },
      { text: 'দামী বই পড়া হয় বলে', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'কিরীট' শব্দের অর্থ কী?",
    answers: [
      { text: 'কানের দুল', isCorrect: false },
      { text: 'মুকুট', isCorrect: true },
      { text: 'হার', isCorrect: false },
      { text: 'চুড়ি', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'হাঁসের পাখায় জল না দাঁড়ানোর সাথে লেখক কাদের তুলনা করেছেন?',
    answers: [
      { text: 'মনোযোগী পাঠক', isCorrect: false },
      { text: 'সমালোচক', isCorrect: false },
      { text: 'জাত-পড়ুয়া', isCorrect: true },
      { text: 'বিজ্ঞ পাঠক', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'অবিমিশ্র' শব্দের অর্থ কী?",
    answers: [
      { text: 'অশুদ্ধ', isCorrect: false },
      { text: 'বিশুদ্ধ', isCorrect: true },
      { text: 'মিশ্রিত', isCorrect: false },
      { text: 'ভেজাল', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'জীবনের প্রতিস্তরে দাগ কেটে চলে কোনটি?',
    answers: [
      { text: 'পড়ার নেশা', isCorrect: false },
      { text: 'অভিজ্ঞতার বৃত্ত', isCorrect: true },
      { text: 'ফ্যাশন', isCorrect: false },
      { text: 'জীবিকা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: "'সওগাত' শব্দের অর্থ কী?",
    answers: [
      { text: 'সংবাদ', isCorrect: false },
      { text: 'উপহার', isCorrect: true },
      { text: 'মেলা', isCorrect: false },
      { text: 'ঘৃণা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'Bengali',
    questionText: 'সরোজ আচার্যের মতে, জীবনকে বুঝতে হলে কী চাই?',
    answers: [
      { text: 'প্রচুর অর্থ', isCorrect: false },
      { text: 'অবসর', isCorrect: false },
      { text: 'সব রকমের বই পড়া', isCorrect: true },
      { text: 'ভ্রমণ', isCorrect: false },
    ],
  },
];
