import type { Question } from './types';

export const newEnglishLevel5Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Arduous' শব্দের সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'আরামদায়ক', isCorrect: false },
      { text: 'শ্রমসাধ্য বা কষ্টকর', isCorrect: true },
      { text: 'খুব সহজ', isCorrect: false },
      { text: 'আনন্দদায়ক', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Afforestation' বলতে কী বোঝায়?",
    answers: [
      { text: 'বন নিধন', isCorrect: false },
      { text: 'বন সংরক্ষণ', isCorrect: false },
      { text: 'বনায়ন', isCorrect: true },
      { text: 'বৃক্ষ রোপণ বন্ধ করা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Baffle' শব্দটির অর্থ কী?",
    answers: [
      { text: 'সহায়তা করা', isCorrect: false },
      { text: 'বিপাকে ফেলা বা হতবুদ্ধি করা', isCorrect: true },
      { text: 'পরিষ্কার করা', isCorrect: false },
      { text: 'উৎসাহিত করা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Blunder' বলতে নিচের কোনটিকে বোঝানো হয়েছে?",
    answers: [
      { text: 'ছোট ভুল', isCorrect: false },
      { text: 'বুদ্ধিমানের কাজ', isCorrect: false },
      { text: 'বোকার মতো বড় ভুল', isCorrect: true },
      { text: 'সঠিক সিদ্ধান্ত', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Causality' শব্দের অর্থ কী?",
    answers: [
      { text: 'সাধারণ ঘটনা', isCorrect: false },
      { text: 'কার্যকারণ সম্পর্ক', isCorrect: true },
      { text: 'আকস্মিক দুর্ঘটনা', isCorrect: false },
      { text: 'কারণহীন বিষয়', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Blueprint' শব্দের সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'নীল রঙের ছবি', isCorrect: false },
      { text: 'নকশা বা পরিকল্পনা', isCorrect: true },
      { text: 'ইতিহাসের বই', isCorrect: false },
      { text: 'সমুদ্রের মানচিত্র', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Afoot' শব্দটির একটি অর্থ হলো 'পায়ে হেঁটে যাওয়া', অন্য অর্থটি কী?",
    answers: [
      { text: 'দ্রুত দৌড়ানো', isCorrect: false },
      { text: 'প্রস্তুতি গ্রহণ করা হচ্ছে এমন', isCorrect: true },
      { text: 'থেমে যাওয়া', isCorrect: false },
      { text: 'পিছিয়ে পড়া', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Barrister' কাদের বলা হয়?",
    answers: [
      { text: 'নিম্ন আদালতের আইনজীবী', isCorrect: false },
      { text: 'উচ্চ আদালতে ওকালতি করার সনদপ্রাপ্ত আইনজীবী', isCorrect: true },
      { text: 'বিচারক', isCorrect: false },
      { text: 'পুলিশ কর্মকর্তা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Astrology' বলতে কোন শাস্ত্রকে বোঝায়?",
    answers: [
      { text: 'উদ্ভিদবিজ্ঞান', isCorrect: false },
      { text: 'জ্যোতিষশাস্ত্র', isCorrect: true },
      { text: 'প্রাণিবিজ্ঞান', isCorrect: false },
      { text: 'রসায়নশাস্ত্র', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Bargain' শব্দের অর্থ কী?",
    answers: [
      { text: 'অতিরিক্ত মূল্য', isCorrect: false },
      { text: 'দরকষাকষি করা', isCorrect: true },
      { text: 'বিনামূল্যে পাওয়া', isCorrect: false },
      { text: 'উপহার দেওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Bestial' শব্দটির অর্থ কী?",
    answers: [
      { text: 'দেবতুল্য', isCorrect: false },
      { text: 'মানুষের মতো', isCorrect: false },
      { text: 'পশুর মতো বা নিষ্ঠুর', isCorrect: true },
      { text: 'দয়ালু', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Canalize' শব্দটির একটি অর্থ 'নদী খনন করা', অন্য অর্থটি কী?",
    answers: [
      { text: 'রাগ প্রকাশ করা', isCorrect: false },
      { text: 'আবেগ বা অনুভূতি গোপন করা', isCorrect: true },
      { text: 'সজোরে চিৎকার করা', isCorrect: false },
      { text: 'গান গাওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Afire' বলতে কী বোঝায়?",
    answers: [
      { text: 'বরফে ঢাকা', isCorrect: false },
      { text: 'পানিতে ভেজা', isCorrect: false },
      { text: 'আগুন ধরেছে এমন', isCorrect: true },
      { text: 'বাতাস বইছে এমন', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Backbite' বলতে কী বোঝায়?",
    answers: [
      { text: 'সামনে প্রশংসা করা', isCorrect: false },
      { text: 'পেছনে নিন্দা করা', isCorrect: true },
      { text: 'কামড় দেওয়া', isCorrect: false },
      { text: 'সাহায্য করা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Circulation' শব্দের অর্থ কোনটি?",
    answers: [
      { text: 'প্রচারণা বা রক্ত সঞ্চালন', isCorrect: true },
      { text: 'স্থির থাকা', isCorrect: false },
      { text: 'বন্ধ হয়ে যাওয়া', isCorrect: false },
      { text: 'গোল হয়ে বসা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Accuracy' শব্দের অর্থ কী?",
    answers: [
      { text: 'ভুলভ্রান্তি', isCorrect: false },
      { text: 'নির্ভুলতা বা নিখুঁতভাব', isCorrect: true },
      { text: 'অলসতা', isCorrect: false },
      { text: 'দ্রুতগতি', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Addiction' বলতে কী বোঝায়?",
    answers: [
      { text: 'মুক্তি', isCorrect: false },
      { text: 'আসক্তি', isCorrect: true },
      { text: 'ঘৃণা', isCorrect: false },
      { text: 'বিরাগ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Ancient' শব্দের সমার্থক শব্দ কোনটি?",
    answers: [
      { text: 'আধুনিক', isCorrect: false },
      { text: 'বর্তমান', isCorrect: false },
      { text: 'প্রাচীন', isCorrect: true },
      { text: 'ভবিষ্যৎ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Appearance' শব্দটির অর্থ কী?",
    answers: [
      { text: 'অদৃশ্য হওয়া', isCorrect: false },
      { text: 'চেহারা বা বাহ্যিক রূপ', isCorrect: true },
      { text: 'বুদ্ধি', isCorrect: false },
      { text: 'স্বভাব', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Availability' বলতে কী বোঝায়?",
    answers: [
      { text: 'দুষ্প্রাপ্যতা', isCorrect: false },
      { text: 'সহজ প্রাপ্যতা', isCorrect: true },
      { text: 'শূন্যতা', isCorrect: false },
      { text: 'অধিক মূল্য', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Awful' শব্দের অর্থ কী?",
    answers: [
      { text: 'চমৎকার', isCorrect: false },
      { text: 'ভয়ংকর বা খুব খারাপ', isCorrect: true },
      { text: 'সুন্দর', isCorrect: false },
      { text: 'শান্ত', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Baboon' বলতে কী বোঝায়?",
    answers: [
      { text: 'এক ধরনের ছোট পাখি', isCorrect: false },
      { text: 'এক ধরনের বড় বানর বা অসভ্য লোক', isCorrect: true },
      { text: 'হরিণ', isCorrect: false },
      { text: 'বাঘ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Barrel' বলতে নিচের কোনটিকে বোঝানো হয়?",
    answers: [
      { text: 'ছোট গ্লাস', isCorrect: false },
      { text: 'পিপা বা সিলিন্ডার আকৃতির পাত্র', isCorrect: true },
      { text: 'কাঠের বাক্স', isCorrect: false },
      { text: 'মাটির চুলা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Basement' বলতে ভবনের কোন অংশকে বোঝায়?",
    answers: [
      { text: 'ছাদ', isCorrect: false },
      { text: 'একদম নিচের তলা', isCorrect: true },
      { text: 'বারান্দা', isCorrect: false },
      { text: 'রান্নাঘর', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Benefit' শব্দের অর্থ কী?",
    answers: [
      { text: 'ক্ষতি', isCorrect: false },
      { text: 'সুবিধা বা উপকার', isCorrect: true },
      { text: 'অসুবিধা', isCorrect: false },
      { text: 'ব্যয়', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Bold' বলতে কেমন ব্যক্তিকে বোঝায়?",
    answers: [
      { text: 'ভীতু', isCorrect: false },
      { text: 'সাহসী', isCorrect: true },
      { text: 'অলস', isCorrect: false },
      { text: 'কৃপণ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Carefree' শব্দের অর্থ কী?",
    answers: [
      { text: 'চিন্তিত', isCorrect: false },
      { text: 'চিন্তামুক্ত বা ভাবনাহীন', isCorrect: true },
      { text: 'সচেতন', isCorrect: false },
      { text: 'দায়িত্বশীল', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Celebrity' বলতে কী বোঝায়?",
    answers: [
      { text: 'সাধারণ মানুষ', isCorrect: false },
      { text: 'খ্যাতিমান বা বিখ্যাত ব্যক্তি', isCorrect: true },
      { text: 'অখ্যাত লোক', isCorrect: false },
      { text: 'অপরাধী', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Chapel' বলতে কী বোঝায়?",
    answers: [
      { text: 'মন্দির', isCorrect: false },
      { text: 'ছোট গির্জা', isCorrect: true },
      { text: 'মসজিদ', isCorrect: false },
      { text: 'খেলার মাঠ', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Classification' শব্দের অর্থ কোনটি?",
    answers: [
      { text: 'এলোমেলো করা', isCorrect: false },
      { text: 'শ্রেণীবিন্যাসকরণ', isCorrect: true },
      { text: 'একীভূত করা', isCorrect: false },
      { text: 'ভেঙে ফেলা', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Acre' (একর) শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈeɪ kə(r)/', isCorrect: true },
      { text: '/ˈæ sɪd/', isCorrect: false },
      { text: '/ækt/', isCorrect: false },
      { text: '/ˈeɪ bl/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Accuracy' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈæk kjə rənt/', isCorrect: false },
      { text: '/ˈæ kjə rəsi/', isCorrect: true },
      { text: '/ə ˈkɔːr dɪŋ li/', isCorrect: false },
      { text: '/ə ˈkjuːt/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Achievement' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ə ˈtʃiːv mənt/', isCorrect: true },
      { text: '/ˈæk tɪ vɪst/', isCorrect: false },
      { text: '/ə ˈtend əns/', isCorrect: false },
      { text: '/ə ˈtræk ʃn/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Actually' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈæk tʃuəl/', isCorrect: false },
      { text: '/ˈæk tʃuəli/', isCorrect: true },
      { text: '/ək ˈsept/', isCorrect: false },
      { text: '/ə ˈsliːp/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Advantage' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/əd ˈvɑːn tɪdʒ/', isCorrect: true },
      { text: '/əd ˈven tʃə(r)/', isCorrect: false },
      { text: '/ˈæd və taɪz/', isCorrect: false },
      { text: '/ə ˈfekt/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Alphabet' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈælfə bet/', isCorrect: true },
      { text: '/ɔːl ˈredi/', isCorrect: false },
      { text: '/ə ˈmʌŋ/', isCorrect: false },
      { text: '/ˈæŋ kl/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Appearance' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ə ˈpɪə rəns/', isCorrect: true },
      { text: '/ə ˈpɪə(r)/', isCorrect: false },
      { text: '/əˈp laɪ/', isCorrect: false },
      { text: '/ˈæp lɪ kəbl/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Average' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈævə rɪdʒ/', isCorrect: true },
      { text: '/ə ˈvɔɪd/', isCorrect: false },
      { text: '/ə ˈweɪk/', isCorrect: false },
      { text: '/ə ˈwɔːrd/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Behaviour' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/bɪ ˈheɪv/', isCorrect: false },
      { text: '/bɪ ˈheɪ vjə(r)/', isCorrect: true },
      { text: '/bɪ ˈlɒŋ/', isCorrect: false },
      { text: '/bɪ ˈliːv/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "'Billion' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈbɪ ljən/', isCorrect: true },
      { text: '/ˈbɪs kɪt/', isCorrect: false },
      { text: '/blæŋk/', isCorrect: false },
      { text: '/bə ˈbuːn/', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/əˈbɪ ləti/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Able', isCorrect: false },
      { text: 'Ability', isCorrect: true },
      { text: 'Abroad', isCorrect: false },
      { text: 'Accept', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/ˈæksɪ dənt/ এটি নিচের কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Accident', isCorrect: true },
      { text: 'Accuracy', isCorrect: false },
      { text: 'Activity', isCorrect: false },
      { text: 'Actual', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/ə ˈtʃiːv/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Achieve', isCorrect: true },
      { text: 'Achievement', isCorrect: false },
      { text: 'Archive', isCorrect: false },
      { text: 'Active', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/əd ˈven tʃə(r)/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Advantage', isCorrect: false },
      { text: 'Adventure', isCorrect: true },
      { text: 'Advertise', isCorrect: false },
      { text: 'Afternoon', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/ˈeɪn ʃənt/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Angel', isCorrect: false },
      { text: 'Ankle', isCorrect: false },
      { text: 'Ancient', isCorrect: true },
      { text: 'Anyway', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/ˈɑːr kɪ tek tʃə(r)/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Architect', isCorrect: false },
      { text: 'Architectural', isCorrect: false },
      { text: 'Architecture', isCorrect: true },
      { text: 'Archaeology', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/ə ˈtræk tɪv/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Attract', isCorrect: false },
      { text: 'Attraction', isCorrect: false },
      { text: 'Attractive', isCorrect: true },
      { text: 'Attention', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/ˈbælkəni/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Balance', isCorrect: false },
      { text: 'Balcony', isCorrect: true },
      { text: 'Balloon', isCorrect: false },
      { text: 'Barrel', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/bɪ ˈheɪv/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Behave', isCorrect: true },
      { text: 'Behaviour', isCorrect: false },
      { text: 'Belief', isCorrect: false },
      { text: 'Believe', isCorrect: false },
    ],
  },
  {
    level: '0.5',
    subject: 'English',
    questionText: "/ˈbrɪ liənt/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Bright', isCorrect: false },
      { text: 'Bridge', isCorrect: false },
      { text: 'Brilliant', isCorrect: true },
      { text: 'Broken', isCorrect: false },
    ],
  },
];
