import type { Question } from './types';

export const newBengaliLevel3Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'মাছি ধরা যে কত শক্ত সে কথা কারা স্বীকার করে নিয়েছেন?',
    answers: [
      { text: 'বিজ্ঞানীরা', isCorrect: false },
      { text: 'সাধারণ মানুষ', isCorrect: false },
      { text: 'পর্যবেক্ষণশীল ব্যক্তি', isCorrect: true },
      { text: 'শিকারীরা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'মাছির সমস্ত মাথা জুড়ে কী বসানো আছে বলে লেখক উল্লেখ করেছেন?',
    answers: [
      { text: 'চুল', isCorrect: false },
      { text: 'ডানা', isCorrect: false },
      { text: 'গাদা গাদা চোখ', isCorrect: true },
      { text: 'শুঁড়', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'মাছির মাথার চোখগুলো কীভাবে বসানো থাকে?',
    answers: [
      { text: 'লম্বালম্বি', isCorrect: false },
      { text: 'আড়াআড়ি', isCorrect: false },
      { text: 'চক্রাকারে', isCorrect: true },
      { text: 'সমান্তরালভাবে', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘আচক্রবালবিস্তৃত সুন্দরী ধরণীর সম্পূর্ণ সৌন্দর্য’ দেখতে চেয়েছিলেন কে?',
    answers: [
      { text: 'প্রমথ চৌধুরী', isCorrect: false },
      { text: 'আনাতোল ফ্রাঁস', isCorrect: true },
      { text: 'সৈয়দ মুজতবা আলী', isCorrect: false },
      { text: 'রবীন্দ্রনাথ ঠাকুর', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'আনাতোল ফ্রাঁসের মতে, মানুষ কীভাবে তার ‘মনের চোখ’ বাড়াতে পারে?',
    answers: [
      { text: 'ব্যায়াম করে', isCorrect: false },
      { text: 'দেশ ভ্রমণ করে', isCorrect: false },
      { text: 'নানা জ্ঞানবিজ্ঞান আয়ত্ত করে', isCorrect: true },
      { text: 'চুপচাপ ভেবে', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'লেখক এদেশের মানুষকে কোন প্রাণীর সাথে তুলনা করেছেন?',
    answers: [
      { text: 'আরব্য উপন্যাসের এক-চোখা দৈত্য', isCorrect: true },
      { text: 'বনের বাঘ', isCorrect: false },
      { text: 'পিঞ্জরাবদ্ধ পাখি', isCorrect: false },
      { text: 'চাতক পাখি', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘বই কেনা’ প্রবন্ধে লেখক কাদের ‘সৌখিন মজদুর’ বলেছেন?',
    answers: [
      { text: 'যারা প্রচুর বই পড়ে', isCorrect: false },
      { text: 'যারা বই কিনে আলমারি সাজায় কিন্তু পড়ে না', isCorrect: true },
      { text: 'যারা সস্তায় বই কেনে', isCorrect: false },
      { text: 'যারা বই ধার দেয়', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'লেখকের মতে, আমাদের দেশে কোন জিনিসের দাম বাড়লে সাধারণ মানুষের জ্ঞানচক্ষু খুলে যায়?',
    answers: [
      { text: 'চাল-ডাল', isCorrect: false },
      { text: 'মাছ-মাংস', isCorrect: false },
      { text: 'বই', isCorrect: true },
      { text: 'পোশাক', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'লেখক ‘বই কেনা’ প্রবন্ধে কোন ফরাসি লেখকের উদাহরণ বারবার দিয়েছেন?',
    answers: [
      { text: 'ভিক্টর হুগো', isCorrect: false },
      { text: 'আনাতোল ফ্রাঁস', isCorrect: true },
      { text: 'মোপাসাঁ', isCorrect: false },
      { text: 'ভলতেয়ার', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘বই কেনা’ প্রবন্ধে উল্লিখিত সেই সুন্দরী ধরণী আসলে কেমন?',
    answers: [
      { text: 'অন্ধকার', isCorrect: false },
      { text: 'কুৎসিত', isCorrect: false },
      { text: 'আচক্রবালবিস্তৃত', isCorrect: true },
      { text: 'সীমিত', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'বই কিনে কেউ কখনও কী হয় না বলে লেখক উল্লেখ করেছেন?',
    answers: [
      { text: 'পন্ডিত', isCorrect: false },
      { text: 'দেউলিয়া', isCorrect: true },
      { text: 'ধনী', isCorrect: false },
      { text: 'বিখ্যাত', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'অধিকাংশ মানুষের কাছে বই কেনাটা কেমন কাজ?',
    answers: [
      { text: 'মহৎ কাজ', isCorrect: false },
      { text: 'বিলাসিতা', isCorrect: false },
      { text: 'বাজে খরচ', isCorrect: true },
      { text: 'ধর্মীয় কাজ', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'যারা বই পড়তে ভালোবাসে না, তারা বই কেনাকে কী মনে করে?',
    answers: [
      { text: 'সময় নষ্ট', isCorrect: false },
      { text: 'টাকা নষ্ট', isCorrect: true },
      { text: 'চোখের কষ্ট', isCorrect: false },
      { text: 'অহংকার', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘বই কেনা’ প্রবন্ধে লেখক পাঠকদের কী হতে অনুরোধ করেছেন?',
    answers: [
      { text: 'গবেষক', isCorrect: false },
      { text: 'লেখক', isCorrect: false },
      { text: 'বই কেনা পাঠক', isCorrect: true },
      { text: 'বই বিক্রেতা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'সাধারণ লোক ফ্রাঁসের কোন কথাটিকে অবাস্তব মনে করতে পারে?',
    answers: [
      { text: 'প্রচুর খাওয়া', isCorrect: false },
      { text: 'চোখের সংখ্যা বাড়ানো', isCorrect: true },
      { text: 'ঘুমানো', isCorrect: false },
      { text: 'টাকা জমানো', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'এদেশের মানুষ বই পড়ার চেয়ে কোনটিকে বেশি গুরুত্ব দেয়?',
    answers: [
      { text: 'অন্নচিন্তা', isCorrect: true },
      { text: 'ভ্রমণ', isCorrect: false },
      { text: 'আড্ডা', isCorrect: false },
      { text: 'খেলাধুলা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'লেখকের মতে বই কেনার অভ্যাসটা আমাদের দেশে কেমন?',
    answers: [
      { text: 'অত্যন্ত ভালো', isCorrect: false },
      { text: 'শোচনীয়', isCorrect: true },
      { text: 'মাঝারি', isCorrect: false },
      { text: 'উন্নতির পথে', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘মনের চোখ’ বলতে লেখক আসলে কী বুঝিয়েছেন?',
    answers: [
      { text: 'চশমা', isCorrect: false },
      { text: 'কল্পনাশক্তি ও প্রজ্ঞা', isCorrect: true },
      { text: 'স্বপ্ন দেখা', isCorrect: false },
      { text: 'চোখের ব্যাধি', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘বই কেনা’ প্রবন্ধের লেখকের নাম কী?',
    answers: [
      { text: 'কাজী নজরুল ইসলাম', isCorrect: false },
      { text: 'সৈয়দ মুজতবা আলী', isCorrect: true },
      { text: 'বঙ্কিমচন্দ্র চট্টোপাধ্যায়', isCorrect: false },
      { text: 'শরৎচন্দ্র', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'আমাদের দেশের মানুষ বই কেনাটাকে অপচয় মনে করে কেন?',
    answers: [
      { text: 'বইয়ের দাম বেশি বলে', isCorrect: false },
      { text: 'পড়ার সময় নেই বলে', isCorrect: false },
      { text: 'গুরুত্ব বোঝে না বলে', isCorrect: false },
      { text: 'উপরের সবকটি', isCorrect: true },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘বই কেনা’ প্রবন্ধে কোন উপন্যাসের দৈত্যের কথা বলা হয়েছে?',
    answers: [
      { text: 'রূপকথা', isCorrect: false },
      { text: 'আরব্য উপন্যাস', isCorrect: true },
      { text: 'ঠাকুমার ঝুলি', isCorrect: false },
      { text: 'হ্যারি পটার', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'মাছির মাথার চারিদিকে চোখ থাকার সুবিধা কী?',
    answers: [
      { text: 'সে দ্রুত উড়তে পারে', isCorrect: false },
      { text: 'সে একই সময়ে সমস্ত পৃথিবী দেখতে পায়', isCorrect: true },
      { text: 'সে খাবার খোঁজে', isCorrect: false },
      { text: 'সে ভয় পায় না', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'জ্ঞান আহরণের প্রধান মাধ্যম কোনটি?',
    answers: [
      { text: 'টেলিভিশন', isCorrect: false },
      { text: 'ইন্টারনেট', isCorrect: false },
      { text: 'বই', isCorrect: true },
      { text: 'রেডিও', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'লেখকের মতে, জীবনের সার্থকতা কিসে?',
    answers: [
      { text: 'টাকা জমানোয়', isCorrect: false },
      { text: 'শুধু খাবার খাওয়ায়', isCorrect: false },
      { text: 'মনকে বিকশিত করায়', isCorrect: true },
      { text: 'ঘুমিয়ে থাকায়', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'যারা বই পড়ে না তাদের পৃথিবী কেমন?',
    answers: [
      { text: 'বিশাল', isCorrect: false },
      { text: 'রঙিন', isCorrect: false },
      { text: 'সংকীর্ণ ও ছোট', isCorrect: true },
      { text: 'বৈচিত্র্যময়', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘আচক্রবাল’ শব্দের অর্থ কী?',
    answers: [
      { text: 'আকাশ পর্যন্ত', isCorrect: false },
      { text: 'দিগন্ত বিস্তৃত', isCorrect: true },
      { text: 'সমুদ্র পর্যন্ত', isCorrect: false },
      { text: 'পাহাড় পর্যন্ত', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'লেখক বই কেনার ক্ষেত্রে কোন দেশের মানুষের অনীহার কথা বলেছেন?',
    answers: [
      { text: 'ইংল্যান্ড', isCorrect: false },
      { text: 'ফ্রান্স', isCorrect: false },
      { text: 'বাংলাদেশ (বাঙালি)', isCorrect: true },
      { text: 'আমেরিকা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'বই পড়লে কিসের মুক্তি ঘটে?',
    answers: [
      { text: 'শরীরের', isCorrect: false },
      { text: 'মনের', isCorrect: true },
      { text: 'বন্দি অবস্থার', isCorrect: false },
      { text: 'কর্মের', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: '‘বই কেনা’ প্রবন্ধটি পাঠের উদ্দেশ্য কী?',
    answers: [
      { text: 'মাছি মারা শেখা', isCorrect: false },
      { text: 'বই পড়ার প্রতি আগ্রহ বাড়ানো', isCorrect: true },
      { text: 'বিদেশি লেখক চেনা', isCorrect: false },
      { text: 'কৃপণতা করা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'Bengali',
    questionText: 'সৈয়দ মুজতবা আলী কোন ধরনের রচনার জন্য বেশি জনপ্রিয়?',
    answers: [
      { text: 'রম্যরচনা ও ভ্রমণকাহিনী', isCorrect: true },
      { text: 'কেবল গম্ভীর প্রবন্ধ', isCorrect: false },
      { text: 'গোয়েন্দা গল্প', isCorrect: false },
      { text: 'নাটক', isCorrect: false },
    ],
  },
];
