import type { Question } from './types';

export const allQuestions: Question[] = [
  // --- শিক্ষা ও মনুষত্ব্য - কাজী মোতাহের হোসেন চৌধুরী ---
  {
    id: 'q1-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের জীবনকে লেখক কিসের সাথে তুলনা করেছেন?',
    answers: [
      { text: 'বিশাল সমুদ্র', isCorrect: false },
      { text: 'আকাশচুম্বী পর্বত', isCorrect: false },
      { text: 'একটি দোতলা ঘর', isCorrect: true },
      { text: 'একটি বহমান নদী', isCorrect: false },
    ],
    explanation: '‘শিক্ষা ও মনুষ্যত্ব’ প্রবন্ধে লেখক মানুষের জীবনকে একটি দোতলা ঘরের সাথে তুলনা করেছেন, যেখানে জীবসত্তা নিচতলা এবং মনুষ্যত্ব উপরতলা।',
  },
  {
    id: 'q2-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের অস্তিত্ব বা জৈবিক চাহিদার স্তরটিকে লেখক কী বলেছেন?',
    answers: [
      { text: 'মনুষ্যত্ব', isCorrect: false },
      { text: 'জীবসত্তা', isCorrect: true },
      { text: 'মানবসত্তা', isCorrect: false },
      { text: 'ব্যক্তিসত্তা', isCorrect: false },
    ],
    explanation: 'লেখক মানুষের জৈবিক অস্তিত্বের স্তরটিকে জীবসত্তা বলেছেন, যা জীবনের প্রয়োজনীয় কিন্তু অপ্রধান দিক।',
  },
  {
    id: 'q3-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'জীবসত্তার ঘর থেকে মনুষ্যত্বের ঘরে ওঠার মই কোনটি?',
    answers: [
      { text: 'ধন-সম্পদ', isCorrect: false },
      { text: 'শিক্ষা', isCorrect: true },
      { text: 'কঠোর পরিশ্রম', isCorrect: false },
      { text: 'সামাজিক মর্যাদা', isCorrect: false },
    ],
    explanation: 'শিক্ষাই হলো সেই মই যা দিয়ে জীবসত্তার স্তর থেকে মনুষ্যত্বের স্তরে উন্নীত হওয়া যায়।',
  },
  {
    id: 'q4-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার আসল কাজ কোনটি?',
    answers: [
      { text: 'জ্ঞান দান করা', isCorrect: false },
      { text: 'চাকরি পাওয়া', isCorrect: false },
      { text: 'মূল্যবোধ সৃষ্টি', isCorrect: true },
      { text: 'নিয়মকানুন শেখানো', isCorrect: false },
    ],
    explanation: 'শিক্ষার প্রধান কাজ হলো মানুষের মধ্যে মূল্যবোধ সৃষ্টি করা এবং মনুষ্যত্বের বিকাশ ঘটানো।',
  },
  {
    id: 'q5-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: "'নিগড়' শব্দের অর্থ কী?",
    answers: [
      { text: 'অন্ধকার', isCorrect: false },
      { text: 'স্বাধীনতা', isCorrect: false },
      { text: 'শৃঙ্খল বা বেড়ি', isCorrect: true },
      { text: 'গভীর গর্ত', isCorrect: false },
    ],
    explanation: "'নিগড়' একটি তৎসম শব্দ, যার অর্থ হলো শৃঙ্খল, বেড়ি বা শিকল।",
  },
  {
    id: 'q6-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মুক্তির জন্য লেখক কয়টি উপায়ের কথা বলেছেন?',
    answers: [
      { text: 'একটি', isCorrect: false },
      { text: 'দুটি', isCorrect: true },
      { text: 'তিনটি', isCorrect: false },
      { text: 'চারটি', isCorrect: false },
    ],
    explanation: 'লেখক মুক্তির জন্য দুটি উপায়ের কথা বলেছেন: একটি অন্ন-বস্ত্রের চিন্তা থেকে মুক্তি, অন্যটি আত্মিক মুক্তি যা শিক্ষার মাধ্যমে আসে।',
  },
  {
    id: 'q7-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: "'লোভে পাপ, পাপে মৃত্যু'—এখানে মৃত্যু বলতে লেখক কোনটিকে বুঝিয়েছেন?",
    answers: [
      { text: 'শারীরিক মৃত্যু', isCorrect: false },
      { text: 'মানসিক রোগ', isCorrect: false },
      { text: 'আত্মিক মৃত্যু', isCorrect: true },
      { text: 'সামাজিক পতন', isCorrect: false },
    ],
    explanation: "এখানে 'মৃত্যু' বলতে আত্মার বিনাশ বা মনুষ্যত্বের অবসান, অর্থাৎ আত্মিক মৃত্যুকে বোঝানো হয়েছে।",
  },
  {
    id: 'q8-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: "শিক্ষার কোন দিকটিকে লেখক 'প্রয়োজনীয় দিক' বা ছোট দিক বলেছেন?",
    answers: [
      { text: 'মনুষ্যত্ব লাভ', isCorrect: false },
      { text: 'অন্ন-বস্ত্রের সমাধান', isCorrect: true },
      { text: 'সাহিত্য চর্চা', isCorrect: false },
      { text: 'বিশ্বভ্রমণ', isCorrect: false },
    ],
    explanation: 'অন্ন-বস্ত্রের সমাধান বা জীবিকা অর্জনের শিক্ষাকে লেখক প্রয়োজনীয় কিন্তু অপ্রধান বা ছোট দিক হিসেবে দেখেছেন।',
  },
  {
    id: 'q9-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'কারারুদ্ধ আহারে তৃপ্ত মানুষের কাছে কোনটি তুচ্ছ মনে হয়?',
    answers: [
      { text: 'সুস্বাদু খাবার', isCorrect: false },
      { text: 'দামী পোশাক', isCorrect: false },
      { text: 'আকাশ-বাতাসের ডাক', isCorrect: true },
      { text: 'কারাপ্রাচীর', isCorrect: false },
    ],
    explanation: 'যে মানুষ শুধু জৈবিক চাহিদা পূরণে মগ্ন, তার কাছে বাইরের জগতের সৌন্দর্য বা মুক্তির আহ্বান (আকাশ-বাতাসের ডাক) তুচ্ছ মনে হয়।',
  },
  {
    id: 'q10-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'কাজী মোতাহের হোসেন চৌধুরী কোন আন্দোলনের সাথে যুক্ত ছিলেন?',
    answers: [
      { text: 'ভাষা আন্দোলন', isCorrect: false },
      { text: 'বুদ্ধির মুক্তি আন্দোলন', isCorrect: true },
      { text: 'অসহযোগ আন্দোলন', isCorrect: false },
      { text: 'নীল বিদ্রোহ', isCorrect: false },
    ],
    explanation: 'কাজী মোতাহের হোসেন চৌধুরী ছিলেন ‘বুদ্ধির মুক্তি আন্দোলন’-এর অন্যতম প্রধান কাণ্ডারি।',
  },
  {
    id: 'q11-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের বিকাশের ক্ষেত্রে লেখক কিসের সার্থকতা তুলে ধরেছেন?',
    answers: [
      { text: 'একটি বিশাল বৃক্ষের', isCorrect: true },
      { text: 'একটি প্রদীপের', isCorrect: false },
      { text: 'একটি নদীর', isCorrect: false },
      { text: 'একটি ফুলের', isCorrect: false },
    ],
    explanation: 'লেখক মানুষের বৃদ্ধিকে একটি বড় গাছের বিকাশের সাথে তুলনা করে দেখিয়েছেন যে, সার্থক বৃদ্ধি শুধু দৈহিক নয়, আত্মিকও বটে।',
  },
  {
    id: 'q12-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'খুৎপিপাসার (ক্ষুধা ও তৃষ্ণা) কাতর মানুষটিকে কী বোঝানো কঠিন?',
    answers: [
      { text: 'অন্ন-বস্ত্রের প্রয়োজনীয়তা', isCorrect: false },
      { text: 'মনুষ্যত্বের মাহাত্ম্য', isCorrect: true },
      { text: 'শিক্ষার গুরুত্ব', isCorrect: false },
      { text: 'টাকা জমানোর কৌশল', isCorrect: false },
    ],
    explanation: 'ক্ষুধা ও তৃষ্ণায় কাতর, অর্থাৎ জীবসত্তার তাড়নায় জর্জরিত মানুষকে মনুষ্যত্বের মাহাত্ম্য বোঝানো অত্যন্ত কঠিন।',
  },
  {
    id: 'q13-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: "'শিক্ষা ও মনুষ্যত্ব' প্রবন্ধটি কোন গ্রন্থ থেকে নেওয়া হয়েছে?",
    answers: [
      { text: 'নূরনামা', isCorrect: false },
      { text: 'সভ্যতার সংকট', isCorrect: false },
      { text: 'সংস্কৃতি কথা', isCorrect: true },
      { text: 'লালসালু', isCorrect: false },
    ],
    explanation: '‘শিক্ষা ও মনুষ্যত্ব’ প্রবন্ধটি কাজী মোতাহের হোসেন চৌধুরীর ‘সংস্কৃতি কথা’ নামক গ্রন্থ থেকে সংকলিত হয়েছে।',
  },
  {
    id: 'q14-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার মাধ্যমে মানুষের মধ্যে কিসের স্বাদ জাগানো হয়?',
    answers: [
      { text: 'অর্থ উপার্জনের', isCorrect: false },
      { text: 'ক্ষমতার', isCorrect: false },
      { text: 'মনুষ্যত্বের', isCorrect: true },
      { text: 'খ্যাতির', isCorrect: false },
    ],
    explanation: 'প্রকৃত শিক্ষা মানুষের মধ্যে মনুষ্যত্বের স্বাদ জাগিয়ে তোলে এবং তাকে আত্মিক মুক্তির পথে পরিচালিত করে।',
  },
  {
    id: 'q15-ben-shikkha-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'প্রকৃত শিক্ষার ফল কী হওয়া উচিত?',
    answers: [
      { text: 'লেফাফাদুরস্তি', isCorrect: false },
      { text: 'জৈবিক মুক্তি ও আত্মিক উন্নয়ন', isCorrect: true },
      { text: 'পদোন্নতি', isCorrect: false },
      { text: 'বিত্তশালী হওয়া', isCorrect: false },
    ],
    explanation: 'প্রকৃত শিক্ষার ফল হলো জৈবিক চাহিদা পূরণের পাশাপাশি আত্মিক উন্নয়ন সাধন, যা মানুষকে الكامل মানুষ হিসেবে গড়ে তোলে।',
  },

  // --- বই পড়া - প্রমথ চৌধুরী ---
  {
    id: 'q1-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'প্রমথ চৌধুরীর মতে মানুষের সর্বশ্রেষ্ঠ শখ কোনটি?',
    answers: [
      { text: 'ভ্রমণ', isCorrect: false },
      { text: 'গান শোনা', isCorrect: false },
      { text: 'বই পড়া', isCorrect: true },
      { text: 'বাগান করা', isCorrect: false },
    ],
    explanation: 'প্রমথ চৌধুরী ‘বই পড়া’ প্রবন্ধে বই পড়াকে মানুষের সর্বশ্রেষ্ঠ শখ হিসেবে অভিহিত করেছেন।',
  },
  {
    id: 'q2-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'লাইব্রেরিকে লেখক কিসের ওপরে স্থান দিয়েছেন?',
    answers: [
      { text: 'বিদ্যালয়', isCorrect: false },
      { text: 'বিশ্ববিদ্যালয়', isCorrect: false },
      { text: 'হাসপাতাল', isCorrect: true },
      { text: 'মন্দির', isCorrect: false },
    ],
    explanation: 'লেখক লাইব্রেরিকে মনের হাসপাতাল বলেছেন এবং এর স্থান হাসপাতালের ওপরে নির্ধারণ করেছেন।',
  },
  {
    id: 'q3-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'লেখক লাইব্রেরিকে স্কুল-কলেজের চেয়ে বেশি গুরুত্ব দিয়েছেন কেন?',
    answers: [
      { text: 'পরীক্ষা নেই বলে', isCorrect: false },
      { text: 'স্বেচ্ছায় স্বচ্ছন্দচিত্তে শিক্ষিত হওয়া যায় বলে', isCorrect: true },
      { text: 'বই কেনা লাগে না', isCorrect: false },
      { text: 'আড্ডা দেওয়া যায়', isCorrect: false },
    ],
    explanation: 'লাইব্রেরিতে মানুষ স্বেচ্ছায় ও আনন্দের সাথে জ্ঞানার্জন করতে পারে, যা স্কুল-কলেজের বাধ্যতামূলক শিক্ষার চেয়ে কার্যকর।',
  },
  {
    id: 'q4-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: "'বই পড়া' প্রবন্ধের মূল বার্তা কী?",
    answers: [
      { text: 'বেশি পরীক্ষা দেওয়া', isCorrect: false },
      { text: 'জিপিএ-৫ পাওয়া', isCorrect: false },
      { text: 'স্বশিক্ষিত হওয়া', isCorrect: true },
      { text: 'সার্টিফিকেট অর্জন', isCorrect: false },
    ],
    explanation: 'প্রবন্ধটির মূল বার্তা হলো প্রাতিষ্ঠানিক শিক্ষার পাশাপাশি স্বশিক্ষার মাধ্যমে প্রকৃত জ্ঞান ও মনুষ্যত্ব অর্জন করা।',
  },
  {
    id: 'q5-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'আমাদের দেশে শিক্ষার ফল দেখা যাচ্ছে না কেন?',
    answers: [
      { text: 'ছাত্ররা অলস', isCorrect: false },
      { text: 'ফল হাতে হাতে পাওয়া যায় না বলে', isCorrect: true },
      { text: 'বইয়ের অভাব', isCorrect: false },
      { text: 'শিক্ষকের অভাব', isCorrect: false },
    ],
    explanation: 'শিক্ষার ফল তাৎক্ষণিকভাবে পাওয়া যায় না, তাই মানুষ এর গুরুত্ব অনুধাবন করতে পারে না এবং সুফল থেকে বঞ্চিত হয়।',
  },
  {
    id: 'q6-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'প্রমথ চৌধুরীর মতে স্বশিক্ষিত মানেই কী?',
    answers: [
      { text: 'পণ্ডিত', isCorrect: false },
      { text: 'শিক্ষিত', isCorrect: false },
      { text: 'সুশিক্ষিত', isCorrect: true },
      { text: 'জ্ঞানী', isCorrect: false },
    ],
    explanation: 'প্রমথ চৌধুরীর মতে, যে ব্যক্তি স্বশিক্ষিত, তিনিই প্রকৃত অর্থে সুশিক্ষিত।',
  },
  {
    id: 'q7-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: "'ব্যাধিই সংক্রামক, স্বাস্থ্য নয়'—এটি কোন প্রসঙ্গে বলা হয়েছে?",
    answers: [
      { text: 'মহামারি', isCorrect: false },
      { text: 'অন্ধ অনুকরণ বা খারাপ শিক্ষার প্রভাব', isCorrect: true },
      { text: 'শারীরিক অসুস্থতা', isCorrect: false },
      { text: 'হাসপাতালের গুরুত্ব', isCorrect: false },
    ],
    explanation: 'খারাপ বিষয় বা কুপরামর্শ যেভাবে দ্রুত ছড়ায়, ভালো বিষয় বা সুশিক্ষা সেভাবে ছড়ায় না—এই প্রসঙ্গে উক্তিটি করা হয়েছে।',
  },
  {
    id: 'q8-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'ডেমোক্রেসি সাহিত্যের সার্থকতা বোঝে না, সে বোঝে শুধু—',
    answers: [
      { text: 'ন্যায়বিচার', isCorrect: false },
      { text: 'সাম্য', isCorrect: false },
      { text: 'টাকা', isCorrect: true },
      { text: 'ক্ষমতা', isCorrect: false },
    ],
    explanation: 'প্রবন্ধে বলা হয়েছে, ডেমোক্রেসি বা গণতন্ত্র সাহিত্যের গুণগত মূল্য নয়, বরং সংখ্যার মূল্য বোঝে, যা টাকার অংকে পরিমাপযোগ্য।',
  },
  {
    id: 'q9-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'দেহের পুষ্টির জন্য যেমন খাদ্য প্রয়োজন, মনের পুষ্টির জন্য কী প্রয়োজন?',
    answers: [
      { text: 'বিশ্রাম', isCorrect: false },
      { text: 'খেলাধুলা', isCorrect: false },
      { text: 'বই পড়া', isCorrect: true },
      { text: 'সঙ্গীত', isCorrect: false },
    ],
    explanation: 'বই পড়া মনের খাদ্যের যোগান দেয়, যা মানসিক বৃদ্ধি ও পুষ্টির জন্য অপরিহার্য।',
  },
  {
    id: 'q10-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'লাইব্রেরির প্রয়োজনীয়তা হাসপাতালের চেয়ে কম নয় কেন?',
    answers: [
      { text: 'ডাক্তার থাকে না', isCorrect: false },
      { text: 'লাইব্রেরি মনের চিকিৎসা করে বলে', isCorrect: true },
      { text: 'সিট পাওয়া যায় না', isCorrect: false },
      { text: 'কোনোটিই নয়', isCorrect: false },
    ],
    explanation: 'হাসপাতাল দেহের চিকিৎসা করে, আর লাইব্রেরি মনের চিকিৎসা করে। সুস্থ জীবনের জন্য দুটিই সমান গুরুত্বপূর্ণ।',
  },
  {
    id: 'q11-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'প্রমথ চৌধুরীর ছদ্মনাম কী ছিল?',
    answers: [
      { text: 'টেকচাঁদ ঠাকুর', isCorrect: false },
      { text: 'বীরবল', isCorrect: true },
      { text: 'ভানুসিংহ', isCorrect: false },
      { text: 'পরশুরাম', isCorrect: false },
    ],
    explanation: 'প্রমথ চৌধুরী ‘বীরবল’ ছদ্মনামে লিখতেন এবং ‘সবুজপত্র’ পত্রিকা সম্পাদনা করতেন।',
  },
  {
    id: 'q12-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষিত সমাজ পাঠবিমুখ হওয়ার কারণ কী?',
    answers: [
      { text: 'সময়ের অভাব', isCorrect: false },
      { text: 'শিক্ষা পদ্ধতির ত্রুটি', isCorrect: true },
      { text: 'ইন্টারনেট', isCorrect: false },
      { text: 'দারিদ্র্য', isCorrect: false },
    ],
    explanation: 'আমাদের ত্রুটিপূর্ণ শিক্ষা ব্যবস্থা শিক্ষার্থীদের পাঠবিমুখ করে তোলে, কারণ এখানে আনন্দ নয়, বাধ্য হয়ে পড়তে হয়।',
  },
  {
    id: 'q13-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: "'বই পড়া' প্রবন্ধটি কোন গ্রন্থ থেকে সংকলিত?",
    answers: [
      { text: 'বীরবলের হালখাতা', isCorrect: false },
      { text: 'প্রবন্ধ সংগ্রহ', isCorrect: true },
      { text: 'সনেট পঞ্চাশৎ', isCorrect: false },
      { text: 'চার-ইয়ারি কথা', isCorrect: false },
    ],
    explanation: '‘বই পড়া’ প্রবন্ধটি প্রমথ চৌধুরীর ‘প্রবন্ধ সংগ্রহ’ নামক গ্রন্থ থেকে সংকলিত হয়েছে।',
  },
  {
    id: 'q14-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'সাহিত্যের রস উপভোগ করতে হলে কী থাকা দরকার?',
    answers: [
      { text: 'অনেক বই', isCorrect: false },
      { text: 'মুক্ত মন', isCorrect: true },
      { text: 'উচ্চ শিক্ষা', isCorrect: false },
      { text: 'আভিজাত্য', isCorrect: false },
    ],
    explanation: 'সাহিত্যের প্রকৃত রস উপভোগ করার জন্য কোনো বাধ্যবাধকতা ছাড়া একটি মুক্ত ও স্বচ্ছন্দ মন থাকা আবশ্যক।',
  },
  {
    id: 'q15-ben-boipora-0.0',
    level: '0.0',
    subject: 'Bengali',
    questionText: 'কাব্যামৃতে আমাদের অরুচি হওয়ার প্রধান কারণ কোনটি?',
    answers: [
      { text: 'ভালো বইয়ের অভাব', isCorrect: false },
      { text: 'জোর করে গেলানো শিক্ষা বা মুখস্থ বিদ্যা', isCorrect: true },
      { text: 'বিজ্ঞান', isCorrect: false },
      { text: 'অলসতা', isCorrect: false },
    ],
    explanation: 'শিক্ষাব্যবস্থায় কাব্য বা সাহিত্যকে জোর করে গেলানো হয় বলে শিক্ষার্থীদের মধ্যে এর প্রতি অরুচি জন্মায়।',
  },

  // --- IPA ---
  {
    id: 'q1-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'What does IPA stand for in linguistics?',
    answers: [
      { text: 'International Phonology Association', isCorrect: false },
      { text: 'International Phonetic Alphabet', isCorrect: true },
      { text: 'Internal Phonetic Arrangement', isCorrect: false },
      { text: 'International Pronunciation Alphabet', isCorrect: false },
    ],
    explanation: 'IPA stands for the International Phonetic Alphabet, a system for representing phonetic sounds with symbols.',
  },
  {
    id: 'q2-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which symbol represents the "sh" sound as in the word "ship"?',
    answers: [
      { text: '/s/', isCorrect: false },
      { text: '/t͡ʃ/', isCorrect: false },
      { text: '/ʃ/', isCorrect: true },
      { text: '/ʒ/', isCorrect: false },
    ],
    explanation: 'The symbol /ʃ/ (esh) represents the voiceless palato-alveolar fricative, commonly known as the "sh" sound.',
  },
  {
    id: 'q3-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'The symbol /θ/ represents which sound?',
    answers: [
      { text: 'The "th" in "mother" (voiced)', isCorrect: false },
      { text: 'The "th" in "think" (voiceless)', isCorrect: true },
      { text: 'The "f" in "phone"', isCorrect: false },
      { text: 'The "t" in "tea"', isCorrect: false },
    ],
    explanation: 'The symbol /θ/ (theta) represents the voiceless dental fricative, as in the word "think" or "bath".',
  },
  {
    id: 'q4-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which of these is the IPA symbol for a voiced bilabial nasal?',
    answers: [
      { text: '/m/', isCorrect: true },
      { text: '/n/', isCorrect: false },
      { text: '/ŋ/', isCorrect: false },
      { text: '/b/', isCorrect: false },
    ],
    explanation: 'The /m/ sound is a voiced bilabial nasal, produced by stopping air with the lips (bilabial) and letting it escape through the nose (nasal).',
  },
  {
    id: 'q5-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'What is the correct IPA transcription for the word "cat"?',
    answers: [
      { text: '/cat/', isCorrect: false },
      { text: '/kat/', isCorrect: false },
      { text: '/kæt/', isCorrect: true },
      { text: '/cet/', isCorrect: false },
    ],
    explanation: 'The word "cat" is transcribed as /kæt/, representing the sounds /k/ (voiceless velar plosive), /æ/ (near-open front unrounded vowel), and /t/ (voiceless alveolar plosive).',
  },
  {
    id: 'q6-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which symbol represents the "schwa" sound, the most common vowel in English?',
    answers: [
      { text: '/æ/', isCorrect: false },
      { text: '/ə/', isCorrect: true },
      { text: '/ʌ/', isCorrect: false },
      { text: '/e/', isCorrect: false },
    ],
    explanation: 'The schwa /ə/ is an unstressed mid-central vowel sound, found in words like "about" (əˈbaʊt) and "sofa" (ˈsoʊfə).',
  },
  {
    id: 'q7-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'The IPA symbol /j/ represents which sound in English?',
    answers: [
      { text: 'The "j" in "jump"', isCorrect: false },
      { text: 'The "y" in "yes"', isCorrect: true },
      { text: 'The "h" in "hot"', isCorrect: false },
      { text: 'The "g" in "gym"', isCorrect: false },
    ],
    explanation: 'In the IPA, /j/ represents the "y" consonant sound (a palatal approximant), as in "yes" /jes/.',
  },
  {
    id: 'q8-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which of the following is a "voiced alveolar fricative"?',
    answers: [
      { text: '/s/', isCorrect: false },
      { text: '/z/', isCorrect: true },
      { text: '/v/', isCorrect: false },
      { text: '/d/', isCorrect: false },
    ],
    explanation: '/z/ is the voiced counterpart to /s/. It is produced by forcing air through a narrow channel at the alveolar ridge, with vocal cord vibration.',
  },
  {
    id: 'q9-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'How is the word "thought" transcribed in IPA?',
    answers: [
      { text: '/θoʊt/', isCorrect: false },
      { text: '/θɔːt/', isCorrect: true },
      { text: '/ðɔːt/', isCorrect: false },
      { text: '/fɔːt/', isCorrect: false },
    ],
    explanation: 'For most General American and RP speakers, "thought" is /θɔːt/. It features the voiceless "th" /θ/, the long open-mid back vowel /ɔː/, and the final /t/.',
  },
  {
    id: 'q10-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which symbol represents a "velar nasal" sound (like the "ng" in "sing")?',
    answers: [
      { text: '/n/', isCorrect: false },
      { text: '/m/', isCorrect: false },
      { text: '/ŋ/', isCorrect: true },
      { text: '/ɲ/', isCorrect: false },
    ],
    explanation: '/ŋ/ (eng) is the velar nasal sound, produced with the back of the tongue against the soft palate (velum).',
  },
  {
    id: 'q11-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which IPA symbol corresponds to the "ch" sound in "church"?',
    answers: [
      { text: '/ʃ/', isCorrect: false },
      { text: '/t͡ʃ/', isCorrect: true },
      { text: '/d͡ʒ/', isCorrect: false },
      { text: '/c/', isCorrect: false },
    ],
    explanation: 'The "ch" sound is an affricate, starting with a /t/ and releasing into a /ʃ/. This combination is represented by /t͡ʃ/.',
  },
  {
    id: 'q12-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'In IPA, what do two dots (ː) following a vowel signify?',
    answers: [
      { text: 'The vowel is nasalized', isCorrect: false },
      { text: 'The vowel is short', isCorrect: false },
      { text: 'The vowel is long', isCorrect: true },
      { text: 'The vowel is stressed', isCorrect: false },
    ],
    explanation: 'The length mark (ː) indicates that the preceding sound is long. It is often used for long vowels like /iː/ in "see" or /ɔː/ in "law".',
  },
  {
    id: 'q13-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which of these is a diphthong?',
    answers: [
      { text: '/iː/', isCorrect: false },
      { text: '/uː/', isCorrect: false },
      { text: '/aɪ/', isCorrect: true },
      { text: '/ɒ/', isCorrect: false },
    ],
    explanation: 'A diphthong is a combination of two adjacent vowel sounds. /aɪ/ as in "my" or "sky" is a common English diphthong.',
  },
  {
    id: 'q14-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'The symbol /ð/ is found in which of the following words?',
    answers: [
      { text: 'Thin', isCorrect: false },
      { text: 'This', isCorrect: true },
      { text: 'Ship', isCorrect: false },
      { text: 'Kite', isCorrect: false },
    ],
    explanation: '/ð/ (eth) represents the voiced "th" sound, as in "this" /ðɪs/ or "mother" /ˈmʌðər/.',
  },
  {
    id: 'q15-eng-ipa-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Which of the following represents a "bilabial plosive"?',
    answers: [
      { text: '/f/', isCorrect: false },
      { text: '/p/', isCorrect: true },
      { text: '/t/', isCorrect: false },
      { text: '/k/', isCorrect: false },
    ],
    explanation: 'A plosive is a stop consonant. /p/ is "bilabial" because it is formed by bringing both lips together. It is also voiceless.',
  },

  // --- A1 Vocabulary ---
  {
    id: 'q1-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Breakfast',
    answers: [
      { text: 'দুপুরের খাবার', isCorrect: false },
      { text: 'প্রাতঃরাশ', isCorrect: true },
      { text: 'রাতের খাবার', isCorrect: false },
      { text: 'বিকেলের নাস্তা', isCorrect: false },
    ],
    explanation: '"Breakfast" is the first meal of the day, eaten in the morning. The Bengali equivalent is "প্রাতঃরাশ" or "সকালের নাস্তা"।',
  },
  {
    id: 'q2-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Window',
    answers: [
      { text: 'দরজা', isCorrect: false },
      { text: 'দেয়াল', isCorrect: false },
      { text: 'জানালা', isCorrect: true },
      { text: 'ছাদ', isCorrect: false },
    ],
    explanation: '"Window" is an opening in the wall of a building to let in light and air. The Bengali word is "জানালা"।',
  },
  {
    id: 'q3-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Village',
    answers: [
      { text: 'শহর', isCorrect: false },
      { text: 'গ্রাম', isCorrect: true },
      { text: 'দেশ', isCorrect: false },
      { text: 'বাজার', isCorrect: false },
    ],
    explanation: '"Village" is a small community or group of houses in a rural area. The Bengali word for it is "গ্রাম"।',
  },
  {
    id: 'q4-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Beautiful',
    answers: [
      { text: 'কুৎসিত', isCorrect: false },
      { text: 'সুন্দর', isCorrect: true },
      { text: 'অপরিচ্ছন্ন', isCorrect: false },
      { text: 'ভয়ঙ্কর', isCorrect: false },
    ],
    explanation: '"Beautiful" is an adjective used to describe something that is pleasing to the senses or mind. The Bengali word is "সুন্দর"।',
  },
  {
    id: 'q5-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Always',
    answers: [
      { text: 'মাঝে মাঝে', isCorrect: false },
      { text: 'কখনও না', isCorrect: false },
      { text: 'সব সময়', isCorrect: true },
      { text: 'শীঘ্রই', isCorrect: false },
    ],
    explanation: '"Always" is an adverb meaning at all times or on all occasions. The Bengali equivalent is "সব সময়" or "সর্বদা"।',
  },
  {
    id: 'q6-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Kitchen',
    answers: [
      { text: 'শোবার ঘর', isCorrect: false },
      { text: 'রান্নাঘর', isCorrect: true },
      { text: 'গোসলখানা', isCorrect: false },
      { text: 'বসার ঘর', isCorrect: false },
    ],
    explanation: '"Kitchen" is a room or area equipped for preparing and cooking food. The Bengali term is "রান্নাঘর"।',
  },
  {
    id: 'q7-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Bridge',
    answers: [
      { text: 'রাস্তা', isCorrect: false },
      { text: 'সাঁকো বা সেতু', isCorrect: true },
      { text: 'পুকুর', isCorrect: false },
      { text: 'পাহাড়', isCorrect: false },
    ],
    explanation: '"Bridge" is a structure carrying a road, path, or railway across a river, or other obstacle. In Bengali, it is called "সাঁকো" or "সেতু"।',
  },
  {
    id: 'q8-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Laugh',
    answers: [
      { text: 'কান্না করা', isCorrect: false },
      { text: 'হাসা', isCorrect: true },
      { text: 'দৌড়ানো', isCorrect: false },
      { text: 'ঘুমানো', isCorrect: false },
    ],
    explanation: '"Laugh" is a verb meaning to make the spontaneous sounds and movements of the face and body that are the instinctive expressions of lively amusement. The Bengali word is "হাসা"।',
  },
  {
    id: 'q9-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Important',
    answers: [
      { text: 'প্রয়োজনীয় বা গুরুত্বপূর্ণ', isCorrect: true },
      { text: 'সহজ', isCorrect: false },
      { text: 'কঠিন', isCorrect: false },
      { text: 'অপ্রয়োজনীয়', isCorrect: false },
    ],
    explanation: '"Important" means of great significance or value. The Bengali equivalent is "প্রয়োজনীয়" or "গুরুত্বপূর্ণ"।',
  },
  {
    id: 'q10-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Weather',
    answers: [
      { text: 'জলবায়ু', isCorrect: false },
      { text: 'আবহাওয়া', isCorrect: true },
      { text: 'পরিবেশ', isCorrect: false },
      { text: 'প্রকৃতি', isCorrect: false },
    ],
    explanation: '"Weather" refers to the state of the atmosphere at a particular place and time as regards heat, cloudiness, dryness, etc. In Bengali, it is "আবহাওয়া"।',
  },
  {
    id: 'q11-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Library',
    answers: [
      { text: 'বাজার', isCorrect: false },
      { text: 'পাঠাগার বা গ্রন্থাগার', isCorrect: true },
      { text: 'খেলার মাঠ', isCorrect: false },
      { text: 'হাসপাতাল', isCorrect: false },
    ],
    explanation: '"Library" is a building or room containing collections of books and periodicals for use or borrowing. In Bengali, it is "পাঠাগার" or "গ্রন্থাগার"।',
  },
  {
    id: 'q12-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Cheap',
    answers: [
      { text: 'দামী', isCorrect: false },
      { text: 'সস্তা', isCorrect: true },
      { text: 'নতুন', isCorrect: false },
      { text: 'পুরাতন', isCorrect: false },
    ],
    explanation: '"Cheap" means low in price. The Bengali word for it is "সস্তা"।',
  },
  {
    id: 'q13-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Medicine',
    answers: [
      { text: 'খাবার', isCorrect: false },
      { text: 'ফল', isCorrect: false },
      { text: 'ওষুধ', isCorrect: true },
      { text: 'পানি', isCorrect: false },
    ],
    explanation: '"Medicine" is a drug or other preparation for the treatment or prevention of disease. The Bengali word is "ওষুধ"।',
  },
  {
    id: 'q14-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Together',
    answers: [
      { text: 'একা একা', isCorrect: false },
      { text: 'একত্রে বা একসাথে', isCorrect: true },
      { text: 'আলাদাভাবে', isCorrect: false },
      { text: 'দূরে', isCorrect: false },
    ],
    explanation: '"Together" means with or in proximity to another person or people. The Bengali equivalent is "একত্রে" or "একসাথে"।',
  },
  {
    id: 'q15-eng-a1-0.0',
    level: '0.0',
    subject: 'English',
    questionText: 'Pardon',
    answers: [
      { text: 'শাস্তি', isCorrect: false },
      { text: 'ক্ষমা করা', isCorrect: true },
      { text: 'অভিনন্দন', isCorrect: false },
      { text: 'ধন্যবাদ', isCorrect: false },
    ],
    explanation: '"Pardon" is the action of forgiving or being forgiven for an error or offense. In Bengali, it means "ক্ষমা করা"।',
  },
];
